// Generated by scripts/build-apps.mjs from experiments/manifest.json.
// Do not edit by hand — edit the manifest.
export const experiments = [
  {
    "slug": "tgsa-p-geometric-skew-lab",
    "title": {
      "zh": "TGSA-P 幾何歪度預判實驗台",
      "en": "TGSA-P Geometric Skew Lookahead Lab"
    },
    "summary": {
      "zh": "真實圖形 R(t) 隨時間演化，虛擬孿生體 V(t) 追蹤它。v0.3 不再只追當下，而是預判 R(t+Δ) 並建立左右極端走廊，讓 V(t) 提前對齊。",
      "en": "A real shape R(t) evolves over time while a virtual twin V(t) tracks it. v0.3 stops chasing the present: it predicts R(t+Δ), builds a left/right extremum corridor, and aligns the twin ahead of time."
    },
    "tags": [
      "SKEW",
      "LOOKAHEAD",
      "ADAPTIVE"
    ],
    "date": "2026-06-29",
    "version": "v0.3",
    "versionCount": 4,
    "related": [
      "rvsc-skew-lab",
      "omega-gap-skew-field-lab"
    ],
    "note": "Renamed at v0.3 from 幾何歪度實驗台 to TGSA-P.",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 21,
    "href": "/experiments/tgsa-p-geometric-skew-lab.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/tgsa-p-geometric-skew-lab.html"
  },
  {
    "slug": "omega-gap-skew-field-lab",
    "title": {
      "zh": "Ω-GAP 幾何歪度場實驗台",
      "en": "Ω-GAP Geometric Skew Field Lab"
    },
    "summary": {
      "zh": "Ω 全向徑展生成理想圓／球面切片，減法拓撲剪出缺口，再轉譯為方向域上的歪度場，最後顯影成不規則形態。整條鏈接在同一個畫面上。",
      "en": "Ω radial expansion produces an ideal circle or sphere slice, subtractive topology cuts gaps into it, the gaps become a skew field over directions, and the field develops into an irregular form — the whole chain on one screen."
    },
    "tags": [
      "OMEGA",
      "TOPOLOGY",
      "SKEW"
    ],
    "date": "2026-06-28",
    "version": "v0.1",
    "versionCount": 1,
    "related": [
      "tgsa-p-geometric-skew-lab"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 22.8,
    "href": "/experiments/omega-gap-skew-field-lab.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/omega-gap-skew-field-lab.html"
  },
  {
    "slug": "pi-circle-curvature",
    "title": {
      "zh": "π、360° 與總曲率",
      "en": "π, 360°, and Total Curvature"
    },
    "summary": {
      "zh": "從中心點出發讓所有方向都延伸相同長度，端點集合就是圓。掃描角度、加減多邊形邊數，看圓周長 C=2πr、曲率 κ=1/r 與總曲率 ∫κds=2π 怎麼同時成立。",
      "en": "Extend every direction the same length from a centre and the endpoints are a circle. Sweep the angle and vary the polygon's sides to watch C=2πr, κ=1/r, and ∫κds=2π hold together."
    },
    "tags": [
      "GEOMETRY",
      "CURVATURE",
      "TEACHING"
    ],
    "date": "2026-06-28",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "sphere-interactive"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 9.8,
    "href": "/experiments/pi-circle-curvature.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/pi-circle-curvature.html"
  },
  {
    "slug": "rvsc-skew-lab",
    "title": {
      "zh": "虛實歪度計算實驗台",
      "en": "Real-Virtual Skew Computation Lab"
    },
    "summary": {
      "zh": "把歪度 K、歪速、歪加速度與粗糙度 Q 當作一組訊號，用自適應演算法 SAA 自動調整虛擬基準更新率、預測阻尼與信心值。",
      "en": "Treats skew K, its velocity, its acceleration, and roughness Q as one signal set, then lets an adaptive algorithm tune the virtual baseline's update rate, prediction damping, and confidence."
    },
    "tags": [
      "SKEW",
      "ADAPTIVE",
      "TIME-SERIES"
    ],
    "date": "2026-06-28",
    "version": "v0.3",
    "versionCount": 4,
    "related": [
      "tgsa-p-geometric-skew-lab"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 31.8,
    "href": "/experiments/rvsc-skew-lab.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/rvsc-skew-lab.html"
  },
  {
    "slug": "sphere-interactive",
    "title": {
      "zh": "三維球面與 4π",
      "en": "The Sphere and 4π"
    },
    "summary": {
      "zh": "把二維的圓提升到三維：端點形成球面 S²，填滿內部得到實心球 B³，而三維的全方向不再是 2π 而是總立體角 4π。高斯總曲率 ∫K dA 同樣是 4π。",
      "en": "Lifts the 2D circle into 3D: the endpoints form the sphere S², filling the interior gives the ball B³, and all directions in 3D total 4π steradians rather than 2π. The Gauss total curvature ∫K dA is also 4π."
    },
    "tags": [
      "GEOMETRY",
      "CURVATURE",
      "3D"
    ],
    "date": "2026-06-28",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "pi-circle-curvature"
    ],
    "note": "Explicitly the 3D companion to the circle page.",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 15,
    "href": "/experiments/sphere-interactive.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/sphere-interactive.html"
  },
  {
    "slug": "skew-predictor",
    "title": {
      "zh": "歪度預測器 SKEW-PRED",
      "en": "Skew Predictor"
    },
    "summary": {
      "zh": "把 π(x)−Li₂(x)、θ(x)−x、ψ(x)−x 當作因果狀態 K、V、A、J、Q，在有限尺度上測試 closure／hold／linear／quadratic 四種預測器並比對誤差。全在瀏覽器端離線計算。",
      "en": "Treats π(x)−Li₂(x), θ(x)−x, and ψ(x)−x as causal states, then tests closure, hold, linear, and quadratic predictors against the truth at finite scale. Runs entirely offline in the browser."
    },
    "tags": [
      "NUMBER-THEORY",
      "PREDICTION",
      "SKEW"
    ],
    "date": "2026-06-27",
    "version": "v0.1",
    "versionCount": 1,
    "related": [],
    "note": "Shares the word skew with the geometry labs and nothing else — this one is analytic number theory.",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 7.3,
    "href": "/experiments/skew-predictor.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/skew-predictor.html"
  },
  {
    "slug": "tcgqt-3d-curvature-voxel-lab",
    "title": {
      "zh": "TCGQT 3D 相位解耦體素場",
      "en": "TCGQT 3D Decoupled Curvature Voxel Lab"
    },
    "summary": {
      "zh": "以低差異序列（Halton 2/3/5）在三維中取樣曲率場，質數與高曲率一起顯影。舊版的 N-loop／Klein 相位耦合保留為獨立模式，方便對照解耦前後的差別。",
      "en": "Samples a 3D curvature field with a low-discrepancy sequence (Halton 2/3/5), developing primes and high curvature together. The older N-loop / Klein-like phase coupling is kept as its own mode so the coupled and decoupled views can be compared."
    },
    "tags": [
      "TCGQT",
      "3D",
      "VOXEL"
    ],
    "date": "2026-06-27",
    "version": "v0.2",
    "versionCount": 2,
    "related": [
      "tcgqt-prime-sphere"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 21.3,
    "href": "/experiments/tcgqt-3d-curvature-voxel-lab.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/tcgqt-3d-curvature-voxel-lab.html"
  },
  {
    "slug": "tcgqt-k-column-inversion",
    "title": {
      "zh": "TCGQT K 欄生成反演實驗台",
      "en": "TCGQT K-Column Generative Inversion"
    },
    "summary": {
      "zh": "把 6k−1 與 6k+1 壓縮成單一欄位 k，分類 PP／PC／CP／CC 與雙半質數，反推公式族，並在滑動窗口上統計各類佔比。",
      "en": "Compresses 6k−1 and 6k+1 into a single column k, classifies each into PP/PC/CP/CC and double-semiprime, inverts formula families, and tracks the class mix over a sliding window."
    },
    "tags": [
      "TCGQT",
      "PRIME",
      "6K±1"
    ],
    "date": "2026-06-27",
    "version": "v0.2",
    "versionCount": 1,
    "related": [
      "tcgqt-prime-triplex"
    ],
    "note": "Only v0.2 exists in the source set.",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 23.5,
    "href": "/experiments/tcgqt-k-column-inversion.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/tcgqt-k-column-inversion.html"
  },
  {
    "slug": "tcgqt-prime-triplex",
    "title": {
      "zh": "TCGQT 質數三重疊圖 TRIPLEX",
      "en": "TCGQT Prime Triplex Overlay"
    },
    "summary": {
      "zh": "閉合篩 A × 生成組合樹 B × 6k±1 車道 C，三層疊在一起看乘法結構與加法位置怎麼交織。刻意做成便宜的疊圖，先看得到再談貴的。",
      "en": "Closure sieve A × generative composite tree B × 6k±1 lanes C, overlaid to show how multiplicative structure and additive position interleave. Deliberately a cheap overlay — see it first, pay for precision later."
    },
    "tags": [
      "TCGQT",
      "PRIME",
      "OVERLAY"
    ],
    "date": "2026-06-27",
    "version": "v0.1",
    "versionCount": 1,
    "related": [
      "tcgqt-k-column-inversion"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 19.3,
    "href": "/experiments/tcgqt-prime-triplex.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/tcgqt-prime-triplex.html"
  },
  {
    "slug": "human-phase-field-agent",
    "title": {
      "zh": "人體相位場因果模擬推演",
      "en": "Human Phase-Field Agent · Causal Simulation"
    },
    "summary": {
      "zh": "示範一個 Agent 如何追蹤相位差、張力邊界與局部展開。全部資料由程式隨機生成，不使用也不推斷任何真實人體資料，不可作為診斷或健康建議。",
      "en": "Demonstrates how an agent tracks phase difference, tension boundaries, and local expansion. Every value is randomly generated: it uses and infers nothing from real human data, and is not a diagnostic or health tool."
    },
    "tags": [
      "AGENT",
      "PHASE-FIELD",
      "SYNTHETIC"
    ],
    "date": "2026-06-20",
    "version": "v0.1",
    "versionCount": 1,
    "related": [],
    "note": "Carries an explicit non-medical boundary statement in the page itself.",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 15.4,
    "href": "/experiments/human-phase-field-agent.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/human-phase-field-agent.html"
  },
  {
    "slug": "tcgqt-prime-lab",
    "title": {
      "zh": "TCGQT 質數實驗台",
      "en": "TCGQT Prime Workbench"
    },
    "summary": {
      "zh": "把已知的質數規律疊在同一個場上：平方螺旋、Ulam 方旋、θ=n、進位螺旋、可約律、孿生連結、間隙著色、模 q 相位。內建知識庫與一段紀律提醒——漂亮 ≠ 新，任何疑似新規律要先贏過篩＋Hardy–Littlewood 基線。",
      "en": "Overlays known prime structure on one field: square spiral, Ulam, θ=n, positional spiral, reducibility, twin links, gap colouring, mod-q phase. Ships a theorem library and a discipline note — pretty is not new, and a suspected pattern has to beat the sieve plus Hardy–Littlewood baseline first."
    },
    "tags": [
      "TCGQT",
      "PRIME",
      "OVERLAY"
    ],
    "date": "2026-06-20",
    "version": "v0.3",
    "versionCount": 2,
    "related": [
      "positional-curvature-engine",
      "tcgqt-prime-sphere"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [
      "fonts.googleapis.com",
      "fonts.gstatic.com"
    ],
    "sizeKb": 29.7,
    "href": "/experiments/tcgqt-prime-lab.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/tcgqt-prime-lab.html"
  },
  {
    "slug": "tcgqt-prime-sphere",
    "title": {
      "zh": "TCGQT 質數球面 · 張力花瓣場",
      "en": "TCGQT Prime Sphere · Tension Petal Field"
    },
    "summary": {
      "zh": "θ=n 捲繞到球面，北極定義為真正的 ∞ 而不是 N。v0.6 加上雙極閉合與有限方向近似的無限維張力花瓣場。頁面自己提醒：格點模式會強化載具秩序，漂亮格線多半是座標系。",
      "en": "θ=n wound onto a sphere whose north pole is genuinely ∞ rather than N. v0.6 adds bipolar closure and a tension petal field approximating infinite dimensions from finite directions. The page warns about its own artefacts: a lattice mode strengthens the carrier's order, and pretty grid lines are usually the coordinate system."
    },
    "tags": [
      "TCGQT",
      "PRIME",
      "SPHERE"
    ],
    "date": "2026-06-20",
    "version": "v0.6",
    "versionCount": 5,
    "related": [
      "tcgqt-prime-lab"
    ],
    "note": "No v0.3 exists in the source set.",
    "sourceOnly": false,
    "externalHosts": [
      "fonts.googleapis.com",
      "fonts.gstatic.com"
    ],
    "sizeKb": 28.8,
    "href": "/experiments/tcgqt-prime-sphere.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/tcgqt-prime-sphere.html"
  },
  {
    "slug": "ouroboros-bench",
    "title": {
      "zh": "類銜尾蛇實驗台 · 時間迴圈 × 空間點陣",
      "en": "Ouroboros Bench · Temporal Loop × Spatial Lattice"
    },
    "summary": {
      "zh": "兩個混沌智能體在時間上呼吸，差異落入鏡／蛇／噪；同一套 K、δ 與呼吸律再推廣到二維格點，用耦合映射 CML 與生命遊戲兩個場域對照。蛇帶在空間裡長成混沌邊緣那條窄縫。",
      "en": "Two chaotic agents breathe in time and their difference falls into mirror, snake, or noise. The same K, δ, and breathing law extend to a 2D lattice, compared across coupled map lattices and Conway's Life. The snake band grows into the narrow seam at the edge of chaos."
    },
    "tags": [
      "CHAOS",
      "CA",
      "LOOP"
    ],
    "date": "2026-06-15",
    "version": "v3",
    "versionCount": 1,
    "related": [],
    "note": "Self-described v3; earlier versions are not in the source set.",
    "sourceOnly": false,
    "externalHosts": [
      "fonts.googleapis.com",
      "fonts.gstatic.com"
    ],
    "sizeKb": 28.5,
    "href": "/experiments/ouroboros-bench.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/ouroboros-bench.html"
  },
  {
    "slug": "transcendent-ring",
    "title": {
      "zh": "超越性閉合 · 無限內外圓場",
      "en": "Transcendent Closure · Field of Infinite Rings"
    },
    "summary": {
      "zh": "一顆是標本，一片才是場。把帶缺口、向外擴大向內緊緻的無限環疊成一整片，用加色混合堆起來，重疊處燒成亮核。log-polar 展開圖說明向內無限緊緻與向外無限擴大在對數尺度上是同一道縫。",
      "en": "One ring is a specimen; a field is the argument. Gapped rings that expand outward and compactify inward are stacked with additive colour until the overlaps burn into bright cores. The log-polar view shows that infinite inward compactification and infinite outward expansion are the same seam on a logarithmic scale."
    },
    "tags": [
      "CLOSURE",
      "INFINITY",
      "FIELD"
    ],
    "date": "2026-06-15",
    "version": "2.0",
    "versionCount": 2,
    "related": [
      "infinity-klein"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [
      "fonts.googleapis.com",
      "fonts.gstatic.com"
    ],
    "sizeKb": 14,
    "href": "/experiments/transcendent-ring.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/transcendent-ring.html"
  },
  {
    "slug": "fdrs-container-identity",
    "title": {
      "zh": "FDRS 容器同一性 · 展開／收斂",
      "en": "FDRS Container Identity · Expand / Converge"
    },
    "summary": {
      "zh": "一個容器 C∗(H) 連續展開與收斂，在立體與展平之間走完整條 Φ，貼面鄰接圖的連通分量 β₀ 始終是同一個指紋。附自動求解 FSM。",
      "en": "A container C∗(H) expands and converges continuously, travelling the whole of Φ between solid and flattened while the adjacency graph's component count β₀ stays the same fingerprint. Includes an automatic solver FSM."
    },
    "tags": [
      "FDRS",
      "TOPOLOGY",
      "IDENTITY"
    ],
    "date": "2026-06-13",
    "version": "v1.0",
    "versionCount": 1,
    "related": [],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 21.2,
    "href": "/experiments/fdrs-container-identity.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/fdrs-container-identity.html"
  },
  {
    "slug": "maze-cache",
    "title": {
      "zh": "迷宮快取 · O(P) 路徑查詢",
      "en": "Maze Cache · O(P) Path Query"
    },
    "summary": {
      "zh": "第一次計算做生成、PDE 與建表；第二次直接從快取載入。之後任何起點到終點的路徑查詢都是 O(P) 即時。快取存在 localStorage，同一迷宮的格點序數固定。",
      "en": "The first run generates the maze, solves the PDE, and builds the table; the second loads from cache. After that any start-to-end path query is O(P). The cache lives in localStorage and a maze's cell ordinals are stable."
    },
    "tags": [
      "MAZE",
      "CACHE",
      "PDE"
    ],
    "date": "2026-06-05",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "hedge-verification-lab"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 12.6,
    "href": "/experiments/maze-cache.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/maze-cache.html"
  },
  {
    "slug": "positional-curvature-engine",
    "title": {
      "zh": "進位曲率引擎 · 質數線 · 可約律",
      "en": "Positional Curvature Engine"
    },
    "summary": {
      "zh": "全數鋪場加上位值環：換基底 b 看同一批整數的相位怎麼變，可約輻條在哪裡現形。點圖上任一點就查它是什麼數。",
      "en": "A full-number field plus a place-value ring: change the base b and watch the same integers' phase shift while reducibility spokes appear. Click any point to ask what number it is."
    },
    "tags": [
      "BASE",
      "CURVATURE",
      "PRIME"
    ],
    "date": "2026-06-05",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "tcgqt-prime-lab"
    ],
    "note": "Shares most of its code with TCGQT 質數實驗台 but frames a different question, so it is kept as its own app.",
    "sourceOnly": false,
    "externalHosts": [
      "fonts.googleapis.com",
      "fonts.gstatic.com"
    ],
    "sizeKb": 22.4,
    "href": "/experiments/positional-curvature-engine.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/positional-curvature-engine.html"
  },
  {
    "slug": "hedge-verification-lab",
    "title": {
      "zh": "對沖驗證實驗台",
      "en": "Hedge Verification Lab"
    },
    "summary": {
      "zh": "在生成的迷宮上比較張力場 T、對沖場 H 與嵌套 H₂ 三種場的行為。",
      "en": "Compares three fields on a generated maze: tension T, hedge H, and nested H₂."
    },
    "tags": [
      "MAZE",
      "FIELD",
      "HEDGE"
    ],
    "date": "2026-06-04",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "maze-cache"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 15,
    "href": "/experiments/hedge-verification-lab.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/hedge-verification-lab.html"
  },
  {
    "slug": "calculus-zoom-strips",
    "title": {
      "zh": "放大就變直 · 薄片加總",
      "en": "Zoom Until Straight · Sum the Strips"
    },
    "summary": {
      "zh": "兩個並排的互動：左邊把曲線放大到看起來是直線（導數就是這一刻的速度），右邊把速度曲線下的區域切成薄片相加（積分就是走過的距離）。同一段 s=t² 的行程，兩邊算出同一個數。",
      "en": "Two interactions side by side: zoom a curve until it looks straight (the derivative is the speed at this instant), and slice the area under the speed curve into strips and add them (the integral is the distance travelled). Same journey s=t², same number from both sides."
    },
    "tags": [
      "CALCULUS",
      "TEACHING",
      "INTERACTIVE"
    ],
    "date": "2026-06-03",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "pi-circle-curvature",
      "sphere-interactive"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 5.5,
    "href": "/experiments/calculus-zoom-strips.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/calculus-zoom-strips.html"
  },
  {
    "slug": "infinity-klein",
    "title": {
      "zh": "∞ → Klein Bottle",
      "en": "∞ → Klein Bottle"
    },
    "summary": {
      "zh": "扭轉環面的橋高 H 一路推到臨界值 H★，看 ∞ 的雙環在什麼點上接成克萊因瓶。",
      "en": "Push the twisted torus's bridge height H toward its critical value H★ and watch where the two loops of ∞ join into a Klein bottle."
    },
    "tags": [
      "TOPOLOGY",
      "3D",
      "KLEIN"
    ],
    "date": "2026-05-31",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "transcendent-ring"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 19.5,
    "href": "/experiments/infinity-klein.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/infinity-klein.html"
  },
  {
    "slug": "infinite-spectrum-taiji",
    "title": {
      "zh": "無限光譜太極",
      "en": "Infinite Spectrum Taiji"
    },
    "summary": {
      "zh": "無極 → 太極 → 坍塌。三種測量前狀態（噪音、白光、黑光）過渡到旋轉的光譜太極，按下觀測就觸發波函數坍塌。",
      "en": "Wuji → Taiji → collapse. Three pre-measurement states (noise, white light, dark light) transition into a spinning spectral taiji; observing triggers the collapse."
    },
    "tags": [
      "QUANTUM",
      "SPECTRUM",
      "TAIJI"
    ],
    "date": "2026-05-30",
    "version": "v2",
    "versionCount": 2,
    "related": [],
    "note": "v2 corrects the taiji S-curve.",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 7.4,
    "href": "/experiments/infinite-spectrum-taiji.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/infinite-spectrum-taiji.html"
  },
  {
    "slug": "prime-fixed-point-attractor",
    "title": {
      "zh": "M6* 質數不動點吸子群",
      "en": "M6* Prime Fixed-Point Attractors"
    },
    "summary": {
      "zh": "把質數畫成 y=0 的不動點線，合數懸浮其上，高度 log(n/p) 是乘法意義上距吸子的對數距離。右上的斜率 m(N) 隨 N 增大趨向 1。",
      "en": "Primes form the fixed-point line at y=0; composites float above it at height log(n/p), their logarithmic distance from the attractor in the multiplicative sense. The slope m(N) tends to 1 as N grows."
    },
    "tags": [
      "PRIME",
      "ATTRACTOR",
      "LOG"
    ],
    "date": "2026-05-30",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "prime-solar-systems"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 9.1,
    "href": "/experiments/prime-fixed-point-attractor.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/prime-fixed-point-attractor.html"
  },
  {
    "slug": "prime-solar-systems",
    "title": {
      "zh": "質數太陽系",
      "en": "Prime Solar Systems"
    },
    "summary": {
      "zh": "每個質數是一個圓心，合數沿徑向臂向外擴張，r = log(n/p)，臂的方向由次級質因數決定——同色就是同一條成因路徑。",
      "en": "Each prime is a centre; composites expand along radial arms at r = log(n/p), with the arm's direction set by the secondary prime factor — same colour means same causal path."
    },
    "tags": [
      "PRIME",
      "ATTRACTOR",
      "RADIAL"
    ],
    "date": "2026-05-30",
    "version": "v1.0",
    "versionCount": 1,
    "related": [
      "prime-fixed-point-attractor"
    ],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 5.9,
    "href": "/experiments/prime-solar-systems.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/prime-solar-systems.html"
  },
  {
    "slug": "gilbreath-mod-lab",
    "title": {
      "zh": "Gilbreath ⋈ mod-m 二階 MOD 規律觀測台",
      "en": "Gilbreath ⋈ mod-m Lab"
    },
    "summary": {
      "zh": "Gilbreath 差分三角與 mod-m 的交叉觀測。三角、殘差與轉移計數全部保持整數，小數點只在按下正規化時出現。",
      "en": "Cross-observation of the Gilbreath difference triangle against mod-m. The triangle, the residuals, and the transition counts stay integral throughout; decimals appear only when normalisation is pressed."
    },
    "tags": [
      "GILBREATH",
      "MOD",
      "PRIME"
    ],
    "date": "2026-05-29",
    "version": "v1.0",
    "versionCount": 1,
    "related": [],
    "note": "A React component, not a standalone page. Published as source until it is given an entry point.",
    "sourceOnly": true,
    "externalHosts": [],
    "sizeKb": 13.9,
    "href": "/experiments/gilbreath-mod-lab.jsx",
    "canonicalUrl": "https://thisoneisneok.com/experiments/gilbreath-mod-lab.jsx"
  },
  {
    "slug": "closure-cognitive-graph",
    "title": {
      "zh": "閉合性認知圖 π₂(Cl)",
      "en": "Closure Cognitive Graph π₂(Cl)"
    },
    "summary": {
      "zh": "元規則層由作者寫下並上鎖，它不規定內容，只規定規則能長成什麼樣；移交之後，下面的規則層交給使用者或 AI 改寫。關掉「度量連接」幾何天花板就失效，關掉「閉合」容器直接破裂。",
      "en": "The meta-rule layer is written by the author and locked: it does not fix content, only what rules may become. After handover the rule layer below is the user's or an AI's to rewrite. Turn off metric connection and the geometric ceiling stops binding; turn off closure and the container breaks."
    },
    "tags": [
      "META-RULE",
      "GRAPH",
      "SANDBOX"
    ],
    "date": "2026-05-24",
    "version": "v1.0",
    "versionCount": 1,
    "related": [],
    "note": "",
    "sourceOnly": false,
    "externalHosts": [],
    "sizeKb": 18.5,
    "href": "/experiments/closure-cognitive-graph.html",
    "canonicalUrl": "https://thisoneisneok.com/experiments/closure-cognitive-graph.html"
  }
] as const;

export const experimentCount = 25;
export const experimentSourceFileCount = 39;
