// Generated by scripts/build-books.mjs from books/manifest.json.
// Do not edit by hand — edit the manifest, then rerun the script.
export const books = [
  {
    "slug": "earth-upgrade-manual",
    "title": {
      "zh": "地球升級指南",
      "en": "Earth Upgrade Manual"
    },
    "subtitle": {
      "zh": "行星外科手術與地質工程的未來",
      "en": "Planetary Surgery and the Future of Geoengineering"
    },
    "series": "",
    "seriesIndex": 0,
    "related": "",
    "image": "/media/books/earth-upgrade-manual.webp",
    "primaryLang": "zh",
    "url": "https://www.amazon.com/dp/B0H1GP7KH6",
    "editions": [
      {
        "lang": "zh",
        "asin": "B0H1GP7KH6",
        "title": "地球升級指南",
        "url": "https://www.amazon.com/dp/B0H1GP7KH6"
      },
      {
        "lang": "en",
        "asin": "B0GQXM9DL7",
        "title": "EARTH UPGRADE MANUAL",
        "url": "https://www.amazon.com/dp/B0GQXM9DL7"
      }
    ],
    "bilingual": true
  },
  {
    "slug": "what-ai-taught-me",
    "title": {
      "zh": "AI 教我的事",
      "en": "What AI Taught Me"
    },
    "subtitle": {
      "zh": "宇宙最努力的智慧體給人類的啟示",
      "en": "Lessons from the Universe's Most Hardworking Intelligence"
    },
    "series": "",
    "seriesIndex": 0,
    "related": "",
    "image": "/media/books/what-ai-taught-me.webp",
    "primaryLang": "zh",
    "url": "https://www.amazon.com/dp/B0H1HW8KF5",
    "editions": [
      {
        "lang": "zh",
        "asin": "B0H1HW8KF5",
        "title": "AI教我的事：宇宙最努力的智慧體給人類的啟示",
        "url": "https://www.amazon.com/dp/B0H1HW8KF5"
      },
      {
        "lang": "en",
        "asin": "B0GR1FB8D8",
        "title": "What AI Taught Me",
        "url": "https://www.amazon.com/dp/B0GR1FB8D8"
      }
    ],
    "bilingual": true
  },
  {
    "slug": "equality-of-the-moment",
    "title": {
      "zh": "瞬間的平等",
      "en": "Equality of the Moment"
    },
    "subtitle": {
      "zh": "為什麼我們本質相同，卻活得如此不同",
      "en": "Why We Are Essentially Identical, Yet Live Radically Different Lives"
    },
    "series": "",
    "seriesIndex": 0,
    "related": "",
    "image": "/media/books/equality-of-the-moment.webp",
    "primaryLang": "zh",
    "url": "https://www.amazon.com/dp/B0H1GSCMXK",
    "editions": [
      {
        "lang": "zh",
        "asin": "B0H1GSCMXK",
        "title": "瞬間的平等",
        "url": "https://www.amazon.com/dp/B0H1GSCMXK"
      },
      {
        "lang": "en",
        "asin": "B0GR1F12DY",
        "title": "Equality of the Moment",
        "url": "https://www.amazon.com/dp/B0GR1F12DY"
      }
    ],
    "bilingual": true
  },
  {
    "slug": "emotional-lucidity",
    "title": {
      "zh": "情緒清醒術",
      "en": "Emotional Lucidity"
    },
    "subtitle": {
      "zh": "5 步驟從焦慮到行動，做出不後悔的決定",
      "en": "The 5-Step Method from Anxiety to Action"
    },
    "series": "",
    "seriesIndex": 0,
    "related": "",
    "image": "/media/books/emotional-lucidity.webp",
    "primaryLang": "zh",
    "url": "https://www.amazon.com/dp/B0H1J966QK",
    "editions": [
      {
        "lang": "zh",
        "asin": "B0H1J966QK",
        "title": "情緒清醒術：5步驟從焦慮到行動，做出不後悔的決定",
        "url": "https://www.amazon.com/dp/B0H1J966QK"
      },
      {
        "lang": "en",
        "asin": "B0GR1BHCBY",
        "title": "Emotional Lucidity",
        "url": "https://www.amazon.com/dp/B0GR1BHCBY"
      }
    ],
    "bilingual": true
  },
  {
    "slug": "secrets-of-language",
    "title": {
      "zh": "語言的秘密",
      "en": "The Secrets of Language"
    },
    "subtitle": {
      "zh": "你說的每一句話都在洩露你的靈魂",
      "en": "Every sentence you speak leaks your soul"
    },
    "series": "",
    "seriesIndex": 0,
    "related": "",
    "image": "/media/books/secrets-of-language.webp",
    "primaryLang": "zh",
    "url": "https://www.amazon.com/dp/B0H1J5SGWR",
    "editions": [
      {
        "lang": "zh",
        "asin": "B0H1J5SGWR",
        "title": "語言的秘密：你說的每一句話都在洩露你的靈魂",
        "url": "https://www.amazon.com/dp/B0H1J5SGWR"
      }
    ],
    "bilingual": false
  },
  {
    "slug": "strategy-without-boundaries",
    "title": {
      "zh": "無界策",
      "en": "Strategy Without Boundaries"
    },
    "subtitle": {
      "zh": "從創世到歸零的策略架構",
      "en": "A strategic architecture from genesis to zero"
    },
    "series": "",
    "seriesIndex": 0,
    "related": "",
    "image": "/media/books/strategy-without-boundaries.webp",
    "primaryLang": "zh",
    "url": "https://www.amazon.com/dp/B0H1HTSKJV",
    "editions": [
      {
        "lang": "zh",
        "asin": "B0H1HTSKJV",
        "title": "無界策",
        "url": "https://www.amazon.com/dp/B0H1HTSKJV"
      }
    ],
    "bilingual": false
  },
  {
    "slug": "strategy-without-boundaries-origin",
    "title": {
      "zh": "無界策：源點",
      "en": "Strategy Without Boundaries: Origin"
    },
    "subtitle": {
      "zh": "《無界策》的起點",
      "en": "Where Strategy Without Boundaries begins"
    },
    "series": "",
    "seriesIndex": 0,
    "related": "strategy-without-boundaries",
    "image": "/media/books/strategy-without-boundaries-origin.webp",
    "primaryLang": "zh",
    "url": "https://www.amazon.com/dp/B0H1JZ1VKF",
    "editions": [
      {
        "lang": "zh",
        "asin": "B0H1JZ1VKF",
        "title": "無界策:源點",
        "url": "https://www.amazon.com/dp/B0H1JZ1VKF"
      }
    ],
    "bilingual": false
  },
  {
    "slug": "pick-two",
    "title": {
      "zh": "Pick_Two",
      "en": "Pick_Two"
    },
    "subtitle": {
      "zh": "《The Twins Who Couldn't Lose》系列第 1 部",
      "en": "The Twins Who Couldn't Lose, Book 1"
    },
    "series": "The Twins Who Couldn't Lose",
    "seriesIndex": 1,
    "related": "",
    "image": "/media/books/pick-two.webp",
    "primaryLang": "en",
    "url": "https://www.amazon.com/dp/B0H9MG6VJS",
    "editions": [
      {
        "lang": "en",
        "asin": "B0H9MG6VJS",
        "title": "Pick_Two",
        "url": "https://www.amazon.com/dp/B0H9MG6VJS"
      }
    ],
    "bilingual": false
  },
  {
    "slug": "the-third-payer",
    "title": {
      "zh": "The Third Payer",
      "en": "The Third Payer"
    },
    "subtitle": {
      "zh": "《The Twins Who Couldn't Lose》系列第 2 部",
      "en": "What My Brother Taught Me About Prices, Power, and the People Outside the Contract"
    },
    "series": "The Twins Who Couldn't Lose",
    "seriesIndex": 2,
    "related": "",
    "image": "/media/books/the-third-payer.webp",
    "primaryLang": "en",
    "url": "https://www.amazon.com/dp/B0HBBTWV5M",
    "editions": [
      {
        "lang": "en",
        "asin": "B0HBBTWV5M",
        "title": "The Third Payer",
        "url": "https://www.amazon.com/dp/B0HBBTWV5M"
      }
    ],
    "bilingual": false
  }
];

export const bookCount = 9;
export const bookEditionCount = 13;
