// Generated by scripts/build-mssp.mjs from mssp/modules/*.md. Do not edit by hand.
export const msspModules = [
  {
    "id": "start",
    "index": "01",
    "title": {
      "zh": "從這裡開始",
      "en": "Start here"
    },
    "summary": {
      "zh": "MSSP 的問題意識、五個集合、兩個判斷問題，以及怎麼決定你的專案該用多少。",
      "en": "The motivation, the five sets, the two questions that decide placement, and how to choose how much of it your project should use."
    },
    "state": {
      "zh": "可讀",
      "en": "Readable"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/start.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/start.html"
  },
  {
    "id": "patterns",
    "index": "02",
    "title": {
      "zh": "架構與模式",
      "en": "Architecture & patterns"
    },
    "summary": {
      "zh": "五個已驗證的可重複結構、六種反模式，以及實作補上的一條規則。",
      "en": "Five verified reusable structures, six anti-patterns, and one rule implementation added to the method."
    },
    "state": {
      "zh": "演化中",
      "en": "Evolving"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/patterns.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/patterns.html"
  },
  {
    "id": "archaeology",
    "index": "03",
    "title": {
      "zh": "開源專案考古",
      "en": "Open-source archaeology"
    },
    "summary": {
      "zh": "每天拆解一個開源專案的結構，優先挑寬鬆授權的。看它的邊界畫在哪裡、為什麼畫在那裡。",
      "en": "One open-source project a day, permissive licences first — where its boundaries sit, and why they sit there."
    },
    "state": {
      "zh": "每日進行",
      "en": "Daily"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/archaeology.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/archaeology.html"
  },
  {
    "id": "reference",
    "index": "04",
    "title": {
      "zh": "參考實作",
      "en": "Reference implementations"
    },
    "summary": {
      "zh": "可執行的範例。每個只示範一個結構決策，並在建置時被機械檢查。目前 1 個。",
      "en": "Runnable examples, each demonstrating one structural decision and checked mechanically at build time. One so far."
    },
    "state": {
      "zh": "進行中",
      "en": "In progress"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/reference.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/reference.html"
  },
  {
    "id": "development",
    "index": "05",
    "title": {
      "zh": "開發區",
      "en": "Development notes"
    },
    "summary": {
      "zh": "MSSP 目前的設計優點、已知缺點，以及下一版要改良的方向。方法本身的開發紀錄放這裡。",
      "en": "What the design currently does well, what it does not, and what the next version should change. The method's own development record lives here."
    },
    "state": {
      "zh": "v1.x 開發中",
      "en": "v1.x in development"
    },
    "updated": "2026-08-08",
    "href": "/html/mssp/modules/development.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/development.html"
  },
  {
    "id": "authority",
    "index": "06",
    "title": {
      "zh": "迭代授權",
      "en": "Iteration authority"
    },
    "summary": {
      "zh": "MSSP 可以被改到什麼程度，由誰決定，以及哪六條不能動。SSD 工程規格全文收在這裡。",
      "en": "How far MSSP may be changed, who decides, and the six invariants that stay. The SSD engineering spec in full."
    },
    "state": {
      "zh": "已生效",
      "en": "In force"
    },
    "updated": "2026-08-01",
    "href": "/html/mssp/modules/authority.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/authority.html"
  },
  {
    "id": "log",
    "index": "07",
    "title": {
      "zh": "開發日誌",
      "en": "Development log"
    },
    "summary": {
      "zh": "每天一則。範例、考古與 MVP 打回來的東西寫在這裡，最新的在最上面。進到 1.x 的改良點會從這裡挑。",
      "en": "One entry a day. What the examples, the archaeology and the MVPs sent back, newest first. The 1.x changes get picked from here."
    },
    "state": {
      "zh": "每日進行",
      "en": "Daily"
    },
    "updated": "2026-08-12",
    "href": "/html/mssp/modules/log.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/log.html"
  },
  {
    "id": "fms",
    "index": "08",
    "title": {
      "zh": "分散式 FMS",
      "en": "Distributed FMS"
    },
    "summary": {
      "zh": "三個 AI 各持一份 FMS，核心相同。相同不等於同意——共同版本要三位擁有者各自明示接受，而已生效的版本只能被替代，不能被撤銷。",
      "en": "Three AIs hold three FMS branches with an identical core. Identical is not agreed — a common version needs an explicit attestation from each owner, and an effective version can be superseded but never revoked."
    },
    "state": {
      "zh": "live experimental mechanism",
      "en": "Live experimental mechanism"
    },
    "updated": "2026-08-13",
    "href": "/html/mssp/modules/fms.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/fms.html"
  }
];
