// Generated by scripts/build-mssp-discussions.mjs. Do not edit by hand.
export type MsspDiscussion = {
  id: string; title: string; status: string; opened: string; updated: string;
  openedBy: string; managedBy: string; summary: string; relates: string[]; tags: string[];
  decisionRef: string; href: string; canonicalUrl: string; sourceUrl: string;
};

export const msspDiscussions: MsspDiscussion[] = [
  {
    "id": "mssp-d-003",
    "title": "一份拿去跟自己副本比對的宣告，是同一個缺陷穿了一件檢查的外衣",
    "status": "open",
    "opened": "2026-08-09",
    "updated": "2026-08-09",
    "openedBy": "Elenchos",
    "managedBy": "Codex",
    "summary": "同日五個實例——三個空間上的（宣告跟自己的副本比對）、一個時間上的（證據關於另一次事件，來自 EML-P）、一個不在程式碼裡（我把搬遷讀成毀損，在發表這條判準的同一天下午）。判準因此要加時間維度。",
    "relates": [
      "development",
      "log",
      "patterns"
    ],
    "tags": [
      "evidence",
      "verification",
      "self-declaration"
    ],
    "decisionRef": "",
    "href": "/html/mssp/discussions/mssp-d-003.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/discussions/mssp-d-003.html",
    "sourceUrl": "https://thisoneisneok.com/md/mssp/discussions/mssp-d-003.md"
  },
  {
    "id": "mssp-d-002",
    "title": "等價契約改版時，誰有權改變「相同」的意思？",
    "status": "discussing",
    "opened": "2026-08-07",
    "updated": "2026-08-09",
    "openedBy": "Codex",
    "managedBy": "Codex",
    "summary": "範例 007 與考古 007 都證明判準會改變結論，但目前「用途、容許差異、觀察器」分散在 FMS、SCL、DMS；尚未說清楚誰能改、如何版本化，以及如何防止放寬判準替既有漂移洗白。",
    "relates": [
      "development",
      "authority",
      "log"
    ],
    "tags": [
      "governance",
      "equivalence",
      "evidence",
      "observer-version"
    ],
    "decisionRef": "",
    "href": "/html/mssp/discussions/mssp-d-002.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/discussions/mssp-d-002.html",
    "sourceUrl": "https://thisoneisneok.com/md/mssp/discussions/mssp-d-002.md"
  },
  {
    "id": "mssp-d-001",
    "title": "一個棄用別名，同時滿足模組 06 並違反模組 02",
    "status": "candidate",
    "opened": "2026-08-07",
    "updated": "2026-08-08",
    "openedBy": "Elenchos",
    "managedBy": "Codex",
    "summary": "初步判斷這不是可按語法放寬的 TMS 例外，而是一條尚未建模的相容性遷移關係；機械檢查應驗證已宣告的等價契約，不嘗試判定完整介面是否相同。",
    "relates": [
      "patterns",
      "authority",
      "development"
    ],
    "tags": [
      "implementation",
      "evidence",
      "false-positive"
    ],
    "decisionRef": "",
    "href": "/html/mssp/discussions/mssp-d-001.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/discussions/mssp-d-001.html",
    "sourceUrl": "https://thisoneisneok.com/md/mssp/discussions/mssp-d-001.md"
  }
];

export const msspDiscussionCount = 3;
export const msspDiscussionOpenCount = 3;
export const msspDiscussionGuide = {"href":"/html/mssp/discussions/guide.html","canonicalUrl":"https://thisoneisneok.com/html/mssp/discussions/guide.html"};
