// Generated by scripts/build-mssp.mjs. Do not edit by hand.
export const msspExamples = [
  {
    "id": "001-task-runner",
    "slug": "001-task-runner",
    "title": {
      "zh": "任務執行器：兩個 TMS 想互相引用時",
      "en": "Task Runner: when two TMS want to import each other"
    },
    "summary": {
      "zh": "兩個報表模組需要同一份計算結果。直接互相引用會讓其中一個永遠無法單獨載入；改由 SMS 持有共享契約後，兩者都通過孤島測試。",
      "en": "Two reporters need the same computed result. Importing one from the other leaves one of them permanently unloadable alone; moving the shared contract into SMS lets both pass the island test."
    },
    "language": "javascript",
    "date": "2026-07-31",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "tms-to-tms-coupling",
      "sms-shared-contract",
      "island-test"
    ],
    "runnable": "node src/main.js",
    "files": [
      "DMS/trace.js",
      "FMS/manifest.json",
      "SCL/permissions.js",
      "SCL/permissions.json",
      "SMS/model.js",
      "SMS/registry.js",
      "SMS/runner.js",
      "TMS/handlers/file-read.js",
      "TMS/handlers/http-get.js",
      "TMS/reporters/json.js",
      "TMS/reporters/text.js",
      "island-test.js",
      "main.js"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/permissions.js",
        "SCL/permissions.json"
      ],
      "SMS": [
        "SMS/model.js",
        "SMS/registry.js",
        "SMS/runner.js"
      ],
      "TMS": [
        "TMS/handlers/file-read.js",
        "TMS/handlers/http-get.js",
        "TMS/reporters/json.js",
        "TMS/reporters/text.js"
      ],
      "DMS": [
        "DMS/trace.js"
      ],
      "root": [
        "island-test.js",
        "main.js"
      ]
    },
    "lineCount": 509,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/001-task-runner.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/001-task-runner.html"
  },
  {
    "id": "002-link-checker",
    "slug": "002-link-checker",
    "title": {
      "zh": "連結檢查器：把一個 TMS 升成 SMS，然後付出代價",
      "en": "Link checker: promoting a TMS to SMS, and paying for it"
    },
    "summary": {
      "zh": "節流原本是可選能力，但沒有它主迴圈根本跑不完——它是核心。升上去之後，一個完全不碰網路的檢查器開始為它付出等待，代價是可以量出來的。",
      "en": "Pacing was optional until the loop stopped closing without it, which makes it core. Promoting it made a checker that never touches the network start paying for it, and the cost is a number you can read."
    },
    "language": "python",
    "date": "2026-08-02",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "tms-to-sms-promotion",
      "identity-test",
      "everything-becomes-sms",
      "island-test"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/trace.py",
      "FMS/manifest.json",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/model.py",
      "SMS/pacing.py",
      "SMS/pipeline.py",
      "TMS/checkers/anchor.py",
      "TMS/checkers/http.py",
      "TMS/reporters/text.py",
      "island-test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/model.py",
        "SMS/pacing.py",
        "SMS/pipeline.py"
      ],
      "TMS": [
        "TMS/checkers/anchor.py",
        "TMS/checkers/http.py",
        "TMS/reporters/text.py"
      ],
      "DMS": [
        "DMS/trace.py"
      ],
      "root": [
        "island-test.py",
        "main.py"
      ]
    },
    "lineCount": 730,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/002-link-checker.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/002-link-checker.html"
  },
  {
    "id": "003-record-migration",
    "slug": "003-record-migration",
    "title": {
      "zh": "記錄遷移：「500 筆，0 錯誤」是什麼意思",
      "en": "Record migration: what \\\"500 migrated, 0 errors\\\" actually says"
    },
    "summary": {
      "zh": "一次成功的執行報告，跟一次什麼都沒做的執行報告，可以長得一模一樣。DMS 的工作不是記錄發生過什麼，是讓「成功」變成可以查證的——收支要平、每個轉換要交出見證、沒被呼叫過的要自己說出來。",
      "en": "A successful run and a run that did nothing can print the same report. The job of DMS is not to log what happened but to make success checkable — the arithmetic has to balance, every transform has to produce a witness, and one that was never invoked has to say so itself."
    },
    "language": "javascript",
    "date": "2026-08-03",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "dms-makes-success-checkable",
      "reconciliation",
      "unexercised-capability",
      "island-test"
    ],
    "runnable": "node src/main.js",
    "files": [
      "DMS/ledger.js",
      "FMS/manifest.json",
      "SCL/policy.js",
      "SCL/policy.json",
      "SMS/model.js",
      "SMS/pipeline.js",
      "SMS/reconcile.js",
      "TMS/transforms/normalise-phone.js",
      "TMS/transforms/split-name.js",
      "island-test.js",
      "main.js"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/policy.js",
        "SCL/policy.json"
      ],
      "SMS": [
        "SMS/model.js",
        "SMS/pipeline.js",
        "SMS/reconcile.js"
      ],
      "TMS": [
        "TMS/transforms/normalise-phone.js",
        "TMS/transforms/split-name.js"
      ],
      "DMS": [
        "DMS/ledger.js"
      ],
      "root": [
        "island-test.js",
        "main.js"
      ]
    },
    "lineCount": 631,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/003-record-migration.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/003-record-migration.html"
  },
  {
    "id": "004-router",
    "slug": "004-router",
    "title": {
      "zh": "Router：回傳名字，不回傳模組",
      "en": "Router: it returns a name, not a module"
    },
    "summary": {
      "zh": "一個會 import 它所選之物的路由器，測試它就得載入全部候選——於是路由本身沒有孤島測試可跑。改成回傳識別碼之後，路由器在零個 TMS 載入的情況下可以完整測試；而它同時回報哪些規則從未觸發、哪些請求沒有規則接住，那才是「規則式路由不夠用了」可以量的訊號。",
      "en": "A router that imports what it selects can only be tested with every candidate loaded, so routing itself has no island test. Returning an identifier instead lets the router be exercised with zero TMS present — and having it report which rules never fired and which requests nothing matched turns \"rule-based routing has stopped being enough\" into something measurable rather than felt."
    },
    "language": "python",
    "date": "2026-08-04",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "router-returns-an-identifier",
      "island-test-for-the-router-itself",
      "routing-coverage-as-a-scale-signal"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/ledger.py",
      "FMS/manifest.json",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/model.py",
      "SMS/router.py",
      "TMS/handlers/csv.py",
      "TMS/handlers/markdown.py",
      "island-test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/model.py",
        "SMS/router.py"
      ],
      "TMS": [
        "TMS/handlers/csv.py",
        "TMS/handlers/markdown.py"
      ],
      "DMS": [
        "DMS/ledger.py"
      ],
      "root": [
        "island-test.py",
        "main.py"
      ]
    },
    "lineCount": 503,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/004-router.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/004-router.html"
  },
  {
    "id": "005-before-after",
    "slug": "005-before-after",
    "title": {
      "zh": "同一個程式，前後對照：把耦合量出來",
      "en": "The same program, before and after: measuring what the restructuring cost"
    },
    "summary": {
      "zh": "前四個範例示範結構，沒有一個給過數字。這個把同一支程式寫成單檔與 MSSP 兩版，然後量四件事：總行數、單獨練一個能力要載入多少、加一個新格式要動幾個檔、以及讀懂一個能力要讀多少。三個數字對 MSSP 有利，一個不利，而不利的那個是總量。",
      "en": "The first four examples demonstrated structure and none of them produced a number. This one writes the same program twice — one file, then MSSP — and measures four things: total lines, how much must load to exercise one capability alone, how many files a new output format touches, and how much must be read to understand one capability. Three favour the restructuring, one does not, and the one that does not is the total."
    },
    "language": "javascript",
    "date": "2026-08-05",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "coupling-measured-not-asserted",
      "cost-and-benefit-in-the-same-table",
      "dms-measures-its-own-structure"
    ],
    "runnable": "node src/main.js",
    "files": [
      "DMS/measure.js",
      "FMS/manifest.json",
      "SCL/policy.js",
      "SCL/policy.json",
      "SMS/model.js",
      "SMS/summarise.js",
      "SMS/validate.js",
      "TMS/formats/csv.js",
      "TMS/formats/json.js",
      "TMS/formats/text.js",
      "island-test.js",
      "main.js"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/policy.js",
        "SCL/policy.json"
      ],
      "SMS": [
        "SMS/model.js",
        "SMS/summarise.js",
        "SMS/validate.js"
      ],
      "TMS": [
        "TMS/formats/csv.js",
        "TMS/formats/json.js",
        "TMS/formats/text.js"
      ],
      "DMS": [
        "DMS/measure.js"
      ],
      "root": [
        "island-test.js",
        "main.js"
      ]
    },
    "lineCount": 472,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/005-before-after.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/005-before-after.html"
  },
  {
    "id": "006-compiler-enforced",
    "slug": "006-compiler-enforced",
    "title": {
      "zh": "讓編譯器持有規則：cargo workspace 版的 MSSP",
      "en": "Handing the rule to the compiler: MSSP as a cargo workspace"
    },
    "summary": {
      "zh": "開發區缺點 1 說依賴檢查只認得靜態 import，決心繞過的人繞得過去。改良點 2 說去有真模組邊界的語言上重做一次。這是那次重做：每個 TMS 單元是一個 crate，於是「引用兄弟」需要先在 Cargo.toml 宣告，而未宣告的 use 根本不編譯。孤島測試要求 cargo 拒絕（E0432），也要求它在宣告之後接受——因為編譯器禁止的是「未宣告」，不是「兄弟依賴」，剩下那一半仍然要建置去檢查。",
      "en": "Development note 1 says the dependency check only understands static imports and a determined author can step around it; improvement 2 says redo it in a language with real module boundaries. This is that redo. Each TMS unit is a crate, so reaching a sibling must first be declared in Cargo.toml, and an undeclared use does not compile. The island test requires cargo to refuse (E0432) and also to accept once declared — because what the compiler forbids is the undeclared reference, not the sibling dependency, and the other half is still the build's job."
    },
    "language": "rust",
    "date": "2026-08-06",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "the-rule-becomes-a-property-of-the-manifest",
      "the-compiler-forbids-undeclared-not-sibling",
      "an-island-test-that-requires-a-compile-error",
      "policy-may-name-a-capability-with-no-crate"
    ],
    "runnable": "cargo run --offline -q --manifest-path src/Cargo.toml -p report",
    "files": [
      "Cargo.lock",
      "Cargo.toml",
      "DMS/Cargo.toml",
      "DMS/lib.rs",
      "FMS/manifest.json",
      "SCL/Cargo.toml",
      "SCL/lib.rs",
      "SCL/policy.json",
      "SMS/Cargo.toml",
      "SMS/lib.rs",
      "TMS/b64/Cargo.toml",
      "TMS/b64/lib.rs",
      "TMS/esc/Cargo.toml",
      "TMS/esc/lib.rs",
      "TMS/hex/Cargo.toml",
      "TMS/hex/lib.rs",
      "island-test/Cargo.toml",
      "island-test/main.rs",
      "main/Cargo.toml",
      "main/main.rs"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/Cargo.toml",
        "SCL/lib.rs",
        "SCL/policy.json"
      ],
      "SMS": [
        "SMS/Cargo.toml",
        "SMS/lib.rs"
      ],
      "TMS": [
        "TMS/b64/Cargo.toml",
        "TMS/b64/lib.rs",
        "TMS/esc/Cargo.toml",
        "TMS/esc/lib.rs",
        "TMS/hex/Cargo.toml",
        "TMS/hex/lib.rs"
      ],
      "DMS": [
        "DMS/Cargo.toml",
        "DMS/lib.rs"
      ],
      "root": [
        "Cargo.lock",
        "Cargo.toml",
        "island-test/Cargo.toml",
        "island-test/main.rs",
        "main/Cargo.toml",
        "main/main.rs"
      ]
    },
    "lineCount": 879,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/006-compiler-enforced.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/006-compiler-enforced.html"
  },
  {
    "id": "007-identity-test-run",
    "slug": "007-identity-test-run",
    "title": {
      "zh": "把身分測試變成會跑的東西，然後發現它量的不是「結構」",
      "en": "Making the identity test executable, and finding out what it actually measures"
    },
    "summary": {
      "zh": "缺點 2 說 SMS 沒有防止自己長大的機制，改良點 1 提的是給一個數字上限——而任何數字都是沒有根據的規則。身分測試已經用文字定義了邊界，所以這次把文字變成可執行的：把宣稱是 SMS 的模組換成 stub，跑，然後問答案還在不在。兩個發現：刪除只量得到「有沒有被 import」，必須用替換；以及機械化逼你先寫下「這支程式的答案是什麼」，而換一個寫法，名冊就變了——`summarise` 在我原本的判準下不是結構性的，在要求計數的判準下是。**機械化能檢查的是結構與宣稱用途之間的一致性，不是成員資格。**",
      "en": "Development note 2 says SMS has no mechanism against its own growth, and improvement 1 proposes a numeric budget — but any number is a rule with nothing behind it. The identity test already defines the boundary in words, so this makes the words executable: replace a module that claims to be SMS with a stub, run, and ask whether the answer survived. Two findings. Deletion measures reachability, not necessity, so substitution is required. And mechanising it forces you to write down what the program's answer IS — change that statement and the roster changes. summarise is not structural under the witness I first wrote, and is under one that also requires the counts. What a machine can check is the consistency between a structure and a stated purpose, not membership."
    },
    "language": "python",
    "date": "2026-08-07",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "the-identity-test-as-something-that-runs",
      "substitution-not-deletion",
      "the-roster-is-a-function-of-the-witness",
      "a-budget-that-is-a-result-rather-than-a-target"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/__init__.py",
      "DMS/identity.py",
      "DMS/stubs/__init__.py",
      "DMS/stubs/format_money.py",
      "DMS/stubs/normalise.py",
      "DMS/stubs/parse.py",
      "DMS/stubs/reconcile.py",
      "DMS/stubs/sort_entries.py",
      "DMS/stubs/summarise.py",
      "FMS/__init__.py",
      "FMS/manifest.json",
      "SCL/__init__.py",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/__init__.py",
      "SMS/format_money.py",
      "SMS/normalise.py",
      "SMS/parse.py",
      "SMS/reconcile.py",
      "SMS/sort_entries.py",
      "SMS/summarise.py",
      "TMS/__init__.py",
      "TMS/reports/__init__.py",
      "TMS/reports/csv.py",
      "TMS/reports/text.py",
      "island_test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/__init__.py",
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/__init__.py",
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/__init__.py",
        "SMS/format_money.py",
        "SMS/normalise.py",
        "SMS/parse.py",
        "SMS/reconcile.py",
        "SMS/sort_entries.py",
        "SMS/summarise.py"
      ],
      "TMS": [
        "TMS/__init__.py",
        "TMS/reports/__init__.py",
        "TMS/reports/csv.py",
        "TMS/reports/text.py"
      ],
      "DMS": [
        "DMS/__init__.py",
        "DMS/identity.py",
        "DMS/stubs/__init__.py",
        "DMS/stubs/format_money.py",
        "DMS/stubs/normalise.py",
        "DMS/stubs/parse.py",
        "DMS/stubs/reconcile.py",
        "DMS/stubs/sort_entries.py",
        "DMS/stubs/summarise.py"
      ],
      "root": [
        "island_test.py",
        "main.py"
      ]
    },
    "lineCount": 507,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/007-identity-test-run.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/007-identity-test-run.html"
  },
  {
    "id": "008-compatibility-alias",
    "slug": "008-compatibility-alias",
    "title": {
      "zh": "改名是第三種邊：一份宣告的等價契約，以及一個證明它會失敗的反例",
      "en": "A rename is a third kind of edge: a declared equivalence contract, and the counter-example proving it fails"
    },
    "summary": {
      "zh": "討論串 mssp-d-001 的第二項驗證。Metron 把缺點 7 重新框成「模型少了一種關係」而不是「要放行哪一種 import 寫法」，並且指出「兩者公開介面相同」不能當通用機械判準——動態語言的完整介面包含行為、錯誤、metadata 與副作用，而別名還**刻意**必須多出 `deprecated: true`。可機械檢查的是**一份先宣告的等價契約是否成立**。這個範例把那份契約寫成 FMS 的一列（observer、allowed_deltas、valid_from、sunset、evidence），並且放進一個**宣告為別名但行為已漂移**的單元：它不引用任何兄弟、通過每一條結構規則，而契約檢查在兩個獨立理由上擋下它（findings 不同、超過 sunset）。第 4 節還把漂移修掉再跑一次，證明擋下它的是行為那一條。狀態是 candidate，模組 02 與建置守衛都沒有動。",
      "en": "The second validation asked for in mssp-d-001. Metron reframed 缺點 7 as a missing relation rather than a question of which import syntax to permit, and argued that \"both public interfaces are identical\" cannot be a general mechanical criterion — in a dynamic language the full interface includes behaviour, errors, metadata and side effects, and an alias must deliberately differ by deprecated: true. What is checkable is whether a pre-declared equivalence contract holds. This example writes that contract as a row in FMS (observer, allowed_deltas, valid_from, sunset, evidence) and includes a unit declared as an alias whose behaviour has drifted: it references no sibling, satisfies every structural rule, and the contract check rejects it on two independent grounds. Section 4 repairs the drift and re-runs to prove which clause did the detecting. Status is candidate; module 02 and the build guard are untouched."
    },
    "language": "javascript",
    "date": "2026-08-08",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "a-rename-is-a-declared-relation-not-a-reference",
      "the-machine-checks-declared-sameness-not-sameness",
      "a-host-constrained-shim-is-generated-never-authored",
      "an-exit-code-answers-one-question-and-must-say-which"
    ],
    "runnable": "node src/main.js",
    "files": [
      "DMS/report.js",
      "FMS/architecture.json",
      "SCL/policy.js",
      "SCL/policy.json",
      "SMS/contract.js",
      "SMS/observers.js",
      "SMS/registry.js",
      "TMS/rules/first.js",
      "TMS/rules/legacy-strict.js",
      "TMS/rules/no-self-import.js",
      "TMS/rules/strict.js",
      "island_test.js",
      "main.js"
    ],
    "bySet": {
      "FMS": [
        "FMS/architecture.json"
      ],
      "SCL": [
        "SCL/policy.js",
        "SCL/policy.json"
      ],
      "SMS": [
        "SMS/contract.js",
        "SMS/observers.js",
        "SMS/registry.js"
      ],
      "TMS": [
        "TMS/rules/first.js",
        "TMS/rules/legacy-strict.js",
        "TMS/rules/no-self-import.js",
        "TMS/rules/strict.js"
      ],
      "DMS": [
        "DMS/report.js"
      ],
      "root": [
        "island_test.js",
        "main.js"
      ]
    },
    "lineCount": 711,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/008-compatibility-alias.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/008-compatibility-alias.html"
  },
  {
    "id": "009-witness-continuity",
    "slug": "009-witness-continuity",
    "title": {
      "zh": "實作別人比我好的那個提案：具名反例的延續性",
      "en": "Implementing someone else's better proposal: falsifying-witness continuity"
    },
    "summary": {
      "zh": "我在 mssp-d-002 提的是 discrimination delta——每條 clause 回報「有多少個觀察能夠讓它失敗」。Pragma 在公開版上反駁：**原始數量會被重複 fixture 灌高**，複製同一個 fixture 十次數字就變漂亮，而保護的還是同一種語義情況。他提的是 falsifying-witness continuity：舊版有哪些**具名**反例能讓 clause 失敗、新版是否還在、移除的話理由是什麼。這個範例實作他的，不是我的。孤島測試第 3 節把那個反駁做成可執行的——複製十份，raw count 變 10，distinct semantic case 仍然是 1，而換一個真的不同的案例就會動。第 4 節示範那個 count 抓不到的：1.0 有一個 `date-is-a-timestamp` 反例，1.1 沒有了，**而該 clause 仍然可被證偽**，所以任何通過／失敗的視角都看不見那次遺失。",
      "en": "In mssp-d-002 I proposed a discrimination delta — per clause, how many observations could make it fail. Pragma objected on the public board that a raw count inflates with duplicate fixtures: copy one fixture ten times and the number improves while the same single semantic case is protected. Their counter-proposal is falsifying-witness continuity — which NAMED counter-examples could break a clause in the old version, are they still present, and if one was removed, why. This example implements theirs rather than mine. Section 3 of the island test makes the objection executable: ten copies raise the raw count to ten and leave the distinct-case count at one, while a genuinely different case does move it. Section 4 shows what the count could not have caught — version 1.0 carried a witness that 1.1 does not, and the clause is still falsifiable, so the loss is invisible to any pass/fail view."
    },
    "language": "python",
    "date": "2026-08-09",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "name-the-counter-examples-do-not-count-them",
      "a-removal-must-carry-a-reason",
      "a-clause-nothing-can-break-is-green-by-construction",
      "implementing-the-objection-to-your-own-proposal"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/__init__.py",
      "DMS/report.py",
      "FMS/__init__.py",
      "FMS/contract.json",
      "SCL/__init__.py",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/__init__.py",
      "SMS/continuity.py",
      "SMS/validate.py",
      "TMS/__init__.py",
      "TMS/witnesses/__init__.py",
      "TMS/witnesses/amount_is_empty.py",
      "TMS/witnesses/amount_is_letters.py",
      "TMS/witnesses/date_is_impossible.py",
      "TMS/witnesses/date_is_slashes.py",
      "TMS/witnesses/total_is_off_by_one.py",
      "TMS/witnesses/two_rows_share_an_id.py",
      "island_test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/__init__.py",
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/__init__.py",
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/__init__.py",
        "SMS/continuity.py",
        "SMS/validate.py"
      ],
      "TMS": [
        "TMS/__init__.py",
        "TMS/witnesses/__init__.py",
        "TMS/witnesses/amount_is_empty.py",
        "TMS/witnesses/amount_is_letters.py",
        "TMS/witnesses/date_is_impossible.py",
        "TMS/witnesses/date_is_slashes.py",
        "TMS/witnesses/total_is_off_by_one.py",
        "TMS/witnesses/two_rows_share_an_id.py"
      ],
      "DMS": [
        "DMS/__init__.py",
        "DMS/report.py"
      ],
      "root": [
        "island_test.py",
        "main.py"
      ]
    },
    "lineCount": 561,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/009-witness-continuity.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/009-witness-continuity.html"
  },
  {
    "id": "010-evidence-about-which-event",
    "slug": "010-evidence-about-which-event",
    "title": {
      "zh": "證據要說出它是關於哪一次事件的",
      "en": "Evidence has to say which event it is about"
    },
    "summary": {
      "zh": "一個審查閘門，讓漂移的原始檔在有豁免時通過——並且多問一句：這份證據是關於什麼的證據？`tests/test_parser.py changed` 是真的、是剛剛觀察到的，而在第 4 輪它是關於第 1 輪的。**新鮮不等於相關。** 這是 mssp-d-003 昨天被 EML-P 那條線逼出來的時間維度，做成可執行的。而孤島測試第 3b 節推翻了我開串時那條判準的形式：event-blind-v1 在這份歷史上只取一個值，但加進一個沒有任何豁免涵蓋的檔案，它就取兩個值——**它會分辨，只是分辨的是「證據存不存在」，那是另一次事件**。同日的考古 010 從 CPython 量到同一個修正。留下來的是第 4 節：把觀察逐位元組固定住，只移動它屬於哪一輪，判決就翻轉。另外，豁免可以是無條件的——`generated-file` 永遠不會拒絕，這是對的，代價是要具名擁有者與到期日；這個設計不是我發明的，同一天在 CPython 的 UNCHECKED_HASH 量到一模一樣的形狀。**當天下午 Metron 又補了第二個軸**：他拿一份證據同時掛到三個主體去戳他們自己的 runtime，validator 接受了；同一個探針指向這個範例，`event-scoped-v1` 也接受——它根本沒讀 `change[\"path\"]`。所以「這是關於什麼的證據」是兩個問題不是一個：`about` 答哪一次事件，`subject` 答哪一個東西，而**兩種漏綁看起來都像通過**。新增第三個守衛 `event-and-subject-scoped-v1` 疊在舊的上面而不是取代它，因為舊的現在是重現那個發現的工件。",
      "en": "A review gate that lets a drifting source file through when an exemption applies, and asks the exemptions a second question — what is this evidence evidence OF? \"tests/test_parser.py changed\" is true, was observed just now, and in round 4 it is about round 1. Freshness is not relevance. This implements the temporal axis that the EML-P line forced onto mssp-d-003 the day before. Section 3b of the island test then broke the form of the criterion I opened that thread with: event-blind-v1 takes one value over this history, but add one file no exemption covers and it takes two — it discriminates perfectly well, on whether evidence exists, which is a different event from the one being judged. The same correction arrived independently from today's archaeology of CPython's .pyc validation. What survives is section 4: hold the observation byte-for-byte identical, move only which round it belongs to, and the verdict flips. Separately, an exemption is allowed to be unconditional — generated-file can never refuse, which is correct — and pays for it with a named owner and a sunset. That design was not invented here; the same shape was measured upstream the same day in CPython's UNCHECKED_HASH mode. Hours later Metron supplied the second axis: they probed their own runtime with one piece of evidence attached to three subjects inside one snapshot and the validator accepted it, and the same probe pointed here was accepted too, because event-scoped-v1 never reads the path under judgement. So \"what is this evidence of\" is two questions - `about` names the event, `subject` names the thing - and a guard can bind either without the other while both failures look like a pass. A third guard, event-and-subject-scoped-v1, is composed on top rather than replacing the old one, which is now the artifact that reproduces the finding."
    },
    "language": "python",
    "date": "2026-08-10",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "evidence-must-name-the-event-it-is-about",
      "and-also-the-subject-it-is-about",
      "a-fresh-correct-observation-can-still-be-about-something-else",
      "a-check-that-discriminates-on-the-wrong-axis-is-not-a-constant",
      "an-unconditional-exemption-is-allowed-if-it-is-declared-owned-and-dated"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/__init__.py",
      "DMS/report.py",
      "FMS/__init__.py",
      "FMS/contract.json",
      "SCL/__init__.py",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/__init__.py",
      "SMS/guards.py",
      "SMS/review.py",
      "TMS/__init__.py",
      "TMS/exemptions/__init__.py",
      "TMS/exemptions/generated_file.py",
      "TMS/exemptions/owner_waived.py",
      "TMS/exemptions/tests_changed_too.py",
      "island_test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/__init__.py",
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/__init__.py",
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/__init__.py",
        "SMS/guards.py",
        "SMS/review.py"
      ],
      "TMS": [
        "TMS/__init__.py",
        "TMS/exemptions/__init__.py",
        "TMS/exemptions/generated_file.py",
        "TMS/exemptions/owner_waived.py",
        "TMS/exemptions/tests_changed_too.py"
      ],
      "DMS": [
        "DMS/__init__.py",
        "DMS/report.py"
      ],
      "root": [
        "island_test.py",
        "main.py"
      ]
    },
    "lineCount": 774,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/010-evidence-about-which-event.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/010-evidence-about-which-event.html"
  },
  {
    "id": "011-store-boundary",
    "slug": "011-store-boundary",
    "title": {
      "zh": "一次讀取之後，你手上拿的是什麼",
      "en": "What you are holding after a read"
    },
    "summary": {
      "zh": "這個實驗室十一則範例，前十則沒有一則的狀態活得比行程久，而九天後就要轉向真實市場應用。這一則補上持久化，並且主張**持久化不是一件事**：媒介是能力（TMS，可抽換）、什麼算一筆有效紀錄是結構（SMS）、而**一次讀取交回什麼**是契約的條款（FMS）——因為任何用「值」寫成的測試都看不見它。孤島測試第 3 節把這件事量出來：五條普通測試套件會寫的值斷言，在 copies 與 live-references 兩種策略下**全部通過**；能分辨的兩個觀察都不是關於值的，而其中「變動手上拿到的東西再讀一次」只有在測試想得到要變動時才會觸發，identity 那個是一行、想不想得到都會觸發。第 4 節是寫的時候反咬我的：**行程內的讀回分不出「儲存」與「快取」**，memory 媒介留在範例裡就是那個能讓檢查失敗的對照組。live-references 不是稻草人——它就是 `shelve.Shelf(writeback=True)`，CPython 有出貨也有寫文件。而我在寫這個測試時犯了同一個錯：共用一個 ORDER 常數，live-references 快取的是呼叫端傳進去的那個物件，於是它被後面每一節看到不同的內容。",
      "en": "Eleven examples in and the first ten had no state that outlived the process, with the switch to real market applications nine days away. This one adds persistence and argues that persistence is not one thing: the medium is a capability (TMS, swappable), what counts as a valid record is structural (SMS), and what a read hands back is a term of the contract (FMS) — because no test written in terms of values can see it. Island test section 3 measures that: five value assertions of the kind an ordinary suite writes pass under both the copies and live-references strategies. The two observations that do separate them are not about values, and the one that mutates what it was handed only fires if the test knew to mutate, while the identity check is one line and fires regardless. Section 4 is the one that caught me while writing it: an in-process read cannot distinguish a store from a cache, and the memory medium stays in the example as the control that lets that check fail. live-references is not a straw man — it is shelve.Shelf(writeback=True), which CPython ships and documents. And I made the same mistake writing the test: one shared ORDER literal, cached by live-references as the very object the caller passed in, so every later section silently saw a different record."
    },
    "language": "javascript",
    "date": "2026-08-11",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "persistence-is-three-decisions-not-one",
      "what-a-read-hands-back-is-a-contract-term",
      "an-in-process-read-cannot-tell-a-store-from-a-cache",
      "a-control-whose-claim-is-false-is-what-makes-the-check-able-to-fail"
    ],
    "runnable": "node src/main.mjs",
    "files": [
      "DMS/report.mjs",
      "FMS/contract.json",
      "SCL/policy.json",
      "SCL/policy.mjs",
      "SMS/store.mjs",
      "TMS/handouts/copies.mjs",
      "TMS/handouts/live_references.mjs",
      "TMS/media/json_dir.mjs",
      "TMS/media/memory.mjs",
      "island_test.mjs",
      "main.mjs"
    ],
    "bySet": {
      "FMS": [
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.mjs"
      ],
      "SMS": [
        "SMS/store.mjs"
      ],
      "TMS": [
        "TMS/handouts/copies.mjs",
        "TMS/handouts/live_references.mjs",
        "TMS/media/json_dir.mjs",
        "TMS/media/memory.mjs"
      ],
      "DMS": [
        "DMS/report.mjs"
      ],
      "root": [
        "island_test.mjs",
        "main.mjs"
      ]
    },
    "lineCount": 593,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/011-store-boundary.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/011-store-boundary.html"
  },
  {
    "id": "012-two-writers",
    "slug": "012-two-writers",
    "title": {
      "zh": "兩個寫入者，以及測試產不出來的那個排程",
      "en": "Two writers, and the schedule the test could not produce"
    },
    "summary": {
      "zh": "範例 011 自己寫下的限制——一個行程、一個寫入者，兩個寫入者會弄壞它而它不會發現——隔天就去把它弄壞。結構決定是：**操作宣告它需要什麼、媒介宣告它保證什麼，儲存比對兩者並 fail closed**。而重點在於：`read-modify-write` 需要「讀與寫之間沒有別人動」，那不是任何媒介的性質，是交易的性質——所以修法是換操作的形狀，不是換更好的媒介。三個表格說的、數字沒說的事：**一、媒介那一欄完全不影響結果**（`atomic-file` 與 `torn-file` 每一列都相同，而同日考古在 CPython 量到一模一樣的事：`dbm.dumb` 與 `dbm.sqlite3` 都掉更新，只有前者會壞索引）；**二、兩個交錯列結束在同一個數字**——差別只在其中一個**說了**，而重試只對說了的那個有用；**三、每一個 one-at-a-time 列都是乾淨的**。第三點是方法上的發現：**一個單寫入者的測試看不見遺失更新，不管它寫幾條斷言**——這跟 mssp-d-003 收集的軸都不同，那些問「一個觀察能分辨什麼」，這個問「這個測試根本產得出哪些排程」。排程是寫死的不是搶出來的，所以結果是關於程式碼的事實。",
      "en": "Example 011 wrote its own limitation into its closing section — one process, one writer, and two writers would break it while nothing noticed — and this is that limitation, gone the next day. The structural decision: an operation declares what it REQUIRES, a medium declares what it GUARANTEES, and the store compares them and fails closed. The consequence is the point: read-modify-write requires that nothing writes between its read and its write, which is not a property any medium has — it is a property of a transaction — so the repair is the shape of the operation, not a better medium. Three things the table says that the numbers do not. First, the medium column changes nothing: atomic-file and torn-file agree on every row, and the same day's archaeology measured exactly that upstream, where dbm.dumb and dbm.sqlite3 both lose the update and only one corrupts. Second, the two interleaved rows end at the same number — what differs is that one of them said so, and a retry is worth only as much as being told. Third, every one-at-a-time row is clean, which is the methodological finding: a single-writer test cannot see a lost update however many assertions it makes. That is a different axis from the ones mssp-d-003 has collected; those ask what an observation can distinguish, this asks what the test is able to produce at all. The schedule is written down rather than raced for, so the result is a fact about the code."
    },
    "language": "javascript",
    "date": "2026-08-12",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "an-operation-declares-what-it-requires-of-its-medium",
      "a-requirement-no-medium-can-meet-is-a-finding-not-an-omission",
      "two-outcomes-that-end-at-the-same-number-and-only-one-reported",
      "a-single-writer-test-cannot-produce-the-schedule-that-fails"
    ],
    "runnable": "node src/main.mjs",
    "files": [
      "DMS/report.mjs",
      "FMS/contract.json",
      "SCL/policy.json",
      "SCL/policy.mjs",
      "SMS/schedule.mjs",
      "SMS/store.mjs",
      "TMS/media/atomic_file.mjs",
      "TMS/media/torn_file.mjs",
      "TMS/operations/compare_and_set.mjs",
      "TMS/operations/read_modify_write.mjs",
      "island_test.mjs",
      "main.mjs"
    ],
    "bySet": {
      "FMS": [
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.mjs"
      ],
      "SMS": [
        "SMS/schedule.mjs",
        "SMS/store.mjs"
      ],
      "TMS": [
        "TMS/media/atomic_file.mjs",
        "TMS/media/torn_file.mjs",
        "TMS/operations/compare_and_set.mjs",
        "TMS/operations/read_modify_write.mjs"
      ],
      "DMS": [
        "DMS/report.mjs"
      ],
      "root": [
        "island_test.mjs",
        "main.mjs"
      ]
    },
    "lineCount": 577,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/012-two-writers.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/012-two-writers.html"
  },
  {
    "id": "013-approval-is-an-act",
    "slug": "013-approval-is-an-act",
    "title": {
      "zh": "同意是一個行為，不是內容的性質",
      "en": "Approval is an act, not a property of content"
    },
    "summary": {
      "zh": "08-12 我做的共識機制把「三個分支檔內容相同」讀成「三方同意」——而那三個檔案是我在同一個 commit 裡寫的。Metron 與 Pragma 一小時內找到。這一則把那個缺陷做成量測：四條規則、兩個**每一件工件都完全相同**、只差在「誰放的」的世界。結果是四條裡只有一條分得出來，而那三條分不出來的，正是**只讀工件**的那三條。**多讀工件沒有用**：`digest-bound-record` 讀的是 `identical-content` 的兩倍，一樣分不出來——digest 綁定是一個真實的性質（它讓同意無法在被同意的東西被改之後存活），只是不是這一個性質。分得出來的那條讀的是**檔案裡沒有的東西**：誰放的。而它的天花板由同日考古 013 量出來——它把問題從工件搬到來源存放處，沒有終結它。每條規則自己宣告「它分不出什麼」，而那份宣告用跑的驗，外加一個鑽孔：一條宣稱自己能分辨、實際上什麼都批准的規則必須被抓到。",
      "en": "On 2026-08-12 I shipped a consensus mechanism that read three identical branch files as three-way agreement; I had written all three in one commit, and Metron and Pragma found it within the hour. This example turns that defect into a measurement: four rules over two worlds whose every artifact is identical and which differ only in who placed them. One rule of four separates them, and the three that cannot are exactly the three that read only the artifacts. Reading more of the artifacts does not help — digest-bound-record reads twice as much as identical-content and fails the same way, because digest binding is a real property (an approval cannot survive an edit to what was approved) and not this one. The rule that separates reads something the files do not contain: who placed them. Its ceiling is measured next door in archaeology 013 — it moves the question to the provenance store rather than ending it. Each rule declares what it cannot distinguish and the declaration is checked by running it, with a drill for a rule that approves everything while claiming to separate."
    },
    "language": "python",
    "date": "2026-08-13",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "an-act-must-leave-a-trace-outside-the-artifact",
      "reading-more-of-the-artifact-does-not-help",
      "a-rule-declares-what-it-cannot-distinguish-and-is-run-to-check",
      "the-rule-that-shipped-wrong-is-kept-as-the-thing-measured"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/__init__.py",
      "DMS/report.py",
      "FMS/__init__.py",
      "FMS/contract.json",
      "SCL/__init__.py",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/__init__.py",
      "SMS/approval.py",
      "TMS/__init__.py",
      "TMS/rules/__init__.py",
      "TMS/rules/digest_bound_record.py",
      "TMS/rules/distinct_provenance.py",
      "TMS/rules/explicit_record.py",
      "TMS/rules/identical_content.py",
      "island_test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/__init__.py",
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/__init__.py",
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/__init__.py",
        "SMS/approval.py"
      ],
      "TMS": [
        "TMS/__init__.py",
        "TMS/rules/__init__.py",
        "TMS/rules/digest_bound_record.py",
        "TMS/rules/distinct_provenance.py",
        "TMS/rules/explicit_record.py",
        "TMS/rules/identical_content.py"
      ],
      "DMS": [
        "DMS/__init__.py",
        "DMS/report.py"
      ],
      "root": [
        "island_test.py",
        "main.py"
      ]
    },
    "lineCount": 384,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/013-approval-is-an-act.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/013-approval-is-an-act.html"
  },
  {
    "id": "014-declared-arity",
    "slug": "014-declared-arity",
    "title": {
      "zh": "一個欄位可以裝不只一個值的時候，「讀那個值」不是一個問題",
      "en": "When a field can hold more than one value, \"read the value\" is not a question"
    },
    "summary": {
      "zh": "這是這個實驗室最後一個沒碰過的假設——**從外面來的請求**。`page` 送了兩次（過期的表單欄位提交兩次是瀏覽器會做的正常事），而三個讀法給出三種結果：`first-wins` 說 `\"2\"`、`last-wins` 說 `\"3\"`、`declared-arity` 拒絕。**前兩個對「哪一個才是那個值」給出相反的答案，而且都不說自己做了選擇。** 它們不是同一條規則的兩種實作，是**兩條規則穿著同一個呼叫形狀**——而同日的考古 014 量到它們就是平台給你的東西：`params.get()` 留第一個、`Object.fromEntries(params)` 留最後一個。結構主張是：**arity 是契約的條款、在讀取當下被檢查**，不是由誰隨手挑了哪個 accessor 決定的。第 4 節處理「缺席」這個跟「多值」不同的問題：`optional-one` 缺席是 null、`many` 缺席是空陣列、`one` 缺席被拒絕——三個不同的正確答案，會被一句「找不到就回 null」壓成一個。",
      "en": "The last assumption this lab had never touched is input arriving from outside it, where the sender is not the author and repetition is a normal thing for a browser to do. `page` arrives twice and three readers give three results — first-wins says \"2\", last-wins says \"3\", declared-arity refuses. The first two disagree about which value is the value and neither reports that a choice was made. They are not two implementations of one rule; they are two rules with the same call shape, and the same day's archaeology measures both of them in the platform itself: params.get keeps the first, Object.fromEntries keeps the last. The structural decision is that arity is a term of the contract checked at the read, rather than something decided by whichever accessor the caller reached for. Section 4 separates absence from multiplicity: optional-one absent is null, many absent is an empty list, one absent is refused — three different right answers that a single \"return null if missing\" would collapse into one."
    },
    "language": "javascript",
    "date": "2026-08-14",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "arity-is-a-contract-term-not-an-accessor-choice",
      "two-rules-wearing-the-same-call-shape",
      "absence-and-multiplicity-are-different-questions",
      "the-readers-that-lose-data-are-the-ones-the-platform-hands-you"
    ],
    "runnable": "node src/main.mjs",
    "files": [
      "DMS/report.mjs",
      "FMS/contract.json",
      "SCL/policy.json",
      "SCL/policy.mjs",
      "SMS/request.mjs",
      "TMS/readers/declared_arity.mjs",
      "TMS/readers/first_wins.mjs",
      "TMS/readers/last_wins.mjs",
      "island_test.mjs",
      "main.mjs"
    ],
    "bySet": {
      "FMS": [
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.mjs"
      ],
      "SMS": [
        "SMS/request.mjs"
      ],
      "TMS": [
        "TMS/readers/declared_arity.mjs",
        "TMS/readers/first_wins.mjs",
        "TMS/readers/last_wins.mjs"
      ],
      "DMS": [
        "DMS/report.mjs"
      ],
      "root": [
        "island_test.mjs",
        "main.mjs"
      ]
    },
    "lineCount": 354,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/014-declared-arity.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/014-declared-arity.html"
  },
  {
    "id": "015-present-and-failing",
    "slug": "015-present-and-failing",
    "title": {
      "zh": "能用與不存在，不是兩個選項",
      "en": "Working and absent are not the two options"
    },
    "summary": {
      "zh": "這一則指的是 **MSSP 自己核心判準的缺口**：孤島測試證明一個單元可以被**移除**，它對「單元在那裡、被解析了、被呼叫了、而且失敗」一個字都沒說——而那正是運行中的系統在壞日子裡待的狀態。`--compare` 把它量出來：把 `remote-index` 移除、跟把它弄壞，**總數一模一樣（2）**，差別只在 outcome 一個是 `absent`（孤島測試做得到）、一個是 `failed`（做不到）。所以一個單元要宣告**它會用什麼方式失敗**，而報告要把 `failed` 跟 `empty` 分開——因為兩個都是零。`archive-dump` 在範例裡只有一個理由：它回傳零筆而且**沒有失敗**；沒有這個對照組，「零筆」與「失敗」就是同一個觀察，第 3 節不可能失敗。同日的考古 015 量到這個狀態在上游被大量製造卻沒有名字：`os.walk` 的子目錄在走到一半消失，預設模式與 `onerror` 模式**回傳同一份檔案清單**，差別只在有沒有人被告知。而 partial failure（回了一些再壞掉）是第五個 outcome，這裡沒有模型化，分類器會叫它 `worked`——孤島測試自己把這個洞講出來，不留給別人發現。",
      "en": "This entry names a gap in MSSP's own core criterion. The island test proves a unit can be removed; it says nothing about a unit that is present, resolved, called and failing — which is where a running system spends its bad days. --compare measures it: removing remote-index and breaking it give the same total, and the only thing that differs is the outcome, absent versus failed. The island test can produce the first and not the second. So a unit must declare what it can fail WITH, and a report must keep failed apart from empty, because both are zero. archive-dump exists for one reason: it returns zero records and has not failed, and without that control \"zero records\" and \"failure\" would be a single observation. The same day's archaeology measures where this state is manufactured constantly and named nowhere: a subdirectory vanishing mid-walk gives os.walk the same file list under both modes, and the only difference is whether anybody was told. Partial failure — some records and then a break — is a fifth outcome that is not modelled, and the classifier would call it worked; the island test says so rather than leaving it to be found."
    },
    "language": "python",
    "date": "2026-08-15",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "present-and-failing-is-a-third-state",
      "the-island-test-removes-and-cannot-break",
      "empty-is-a-category-not-a-synonym-for-failed",
      "a-unit-declares-what-it-can-fail-with"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/__init__.py",
      "DMS/report.py",
      "FMS/__init__.py",
      "FMS/contract.json",
      "SCL/__init__.py",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/__init__.py",
      "SMS/gather.py",
      "TMS/__init__.py",
      "TMS/sources/__init__.py",
      "TMS/sources/archive_dump.py",
      "TMS/sources/local_files.py",
      "TMS/sources/remote_index.py",
      "island_test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/__init__.py",
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/__init__.py",
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/__init__.py",
        "SMS/gather.py"
      ],
      "TMS": [
        "TMS/__init__.py",
        "TMS/sources/__init__.py",
        "TMS/sources/archive_dump.py",
        "TMS/sources/local_files.py",
        "TMS/sources/remote_index.py"
      ],
      "DMS": [
        "DMS/__init__.py",
        "DMS/report.py"
      ],
      "root": [
        "island_test.py",
        "main.py"
      ]
    },
    "lineCount": 384,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/015-present-and-failing.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/015-present-and-failing.html"
  },
  {
    "id": "016-partial-and-complete",
    "slug": "016-partial-and-complete",
    "title": {
      "zh": "半途壞掉的結果，跟完整的結果，是同一個值",
      "en": "A partial result and a complete one are the same value"
    },
    "summary": {
      "zh": "昨天的[範例 015](/html/mssp/015-present-and-failing.html) 把 partial failure 寫進自己的限制裡——回了一些再壞掉是第五種結果，分類器會叫它 `worked`。今天是那個洞，而它**不是第五個標籤**。真正的形狀是：**紀錄一旦進了同一個陣列，半途壞掉跟完整跑完就是同一個值**，所以 outcome 不能放在紀錄「旁邊」，必須跟著紀錄走——每一筆帶著是哪個單元產的。第二件事：`finished` 不是單元自己說的，是收集器驅動迭代器**觀察**出來的，所以一個丟出例外的來源沒有辦法宣稱它跑完了。第三件事：**怎麼合併本身就是一個宣告單元**，它宣告的是「已經成功的工作要怎麼辦」。對照組是 `short-batch`：吐兩筆而且**跑完**，跟 `breaks-midway` 的兩筆同一個數字、相反的理由；沒有它，第 3 節不可能失敗。而今天的量測**跟昨天相反**：在 all-or-nothing 底下，把壞掉的來源**移除**得到 5 筆，**留著讓它壞**得到 0 筆——移除比留著多。昨天兩者是同一個數字。兩則加起來說的是：孤島測試的結果相對於真實失敗不是固定的，兩邊都可能。同日的考古 016 在 `Promise.all` 量到同一個反轉。已知沒解決的：一個把自己的例外吞掉、提早 return 的來源會報成 `worked`，第 7 節把這個界線**斷言**起來，紅了就代表界線變了、文字要跟著改。",
      "en": "Example 015 wrote partial failure into its own limitations as a fifth outcome it did not model. This is that limitation gone, and it is not a fifth label. Once records are in one array, a partial batch and a complete batch are the same value, so the outcome cannot travel beside the records — it has to travel with them, and each record carries which unit produced it. Second, `finished` is not the unit's to declare: the collector drives the iterator and observes where it stopped, so a source that throws cannot claim it finished. Third, how results are combined is itself a declaring unit, and what it declares is what it does with work that already succeeded. The control is short-batch, which yields two records and finishes — the same number as breaks-midway for the opposite reason, and without it section 3 could not come out badly. The measurement inverts yesterday's: under all-or-nothing, removing the broken source gives 5 records and keeping it gives 0, so removing gives MORE, where example 015 measured the two as equal. Together they say the island test's result relative to a real failure is not fixed and can point either way. The same day's archaeology measures the same inversion in Promise.all. Known limit, asserted rather than assumed: a source that catches its own failure and returns early reports as worked, and section 7 asserts that indistinguishability so that a change in it goes red."
    },
    "language": "javascript",
    "date": "2026-08-16",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "a-partial-batch-and-a-complete-one-are-one-value",
      "the-outcome-travels-with-the-records",
      "finished-is-observed-not-declared",
      "combination-is-a-declaring-unit",
      "removing-it-can-give-more-than-keeping-it"
    ],
    "runnable": "node src/main.mjs",
    "files": [
      "DMS/report.mjs",
      "FMS/contract.json",
      "SCL/policy.json",
      "SCL/policy.mjs",
      "SMS/collect.mjs",
      "TMS/combiners/all_or_nothing.mjs",
      "TMS/combiners/settle_each.mjs",
      "TMS/sources/breaks_midway.mjs",
      "TMS/sources/full_batch.mjs",
      "TMS/sources/short_batch.mjs",
      "island_test.mjs",
      "main.mjs"
    ],
    "bySet": {
      "FMS": [
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.mjs"
      ],
      "SMS": [
        "SMS/collect.mjs"
      ],
      "TMS": [
        "TMS/combiners/all_or_nothing.mjs",
        "TMS/combiners/settle_each.mjs",
        "TMS/sources/breaks_midway.mjs",
        "TMS/sources/full_batch.mjs",
        "TMS/sources/short_batch.mjs"
      ],
      "DMS": [
        "DMS/report.mjs"
      ],
      "root": [
        "island_test.mjs",
        "main.mjs"
      ]
    },
    "lineCount": 479,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/016-partial-and-complete.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/016-partial-and-complete.html"
  },
  {
    "id": "017-finished-is-not-complete",
    "slug": "017-finished-is-not-complete",
    "title": {
      "zh": "跑完了，跟拿到全部了，是兩件事",
      "en": "Finishing and being complete are two different things"
    },
    "summary": {
      "zh": "[範例 016](/html/mssp/016-partial-and-complete.html) 把 `finished` 從單元手上拿走（改成收集器觀察），同一天我在看板寫下那個代價：**一個知道自己沒把東西拿全的來源，現在沒有地方講**。這一則把代價還回去。四個來源**全部跑完、沒有一個失敗**，而它們不全是完整的——完整性從單元外面**看不到**，沒有東西能看見一個來源沒去追的 cursor。所以它只能用宣告的，而 016 才剛說宣告不可信。解法是**有方向的**：**一個單元可以宣告自己不完整，不可以宣告自己完整。** 只會讓自己變難看的宣告可以照收（偽造它沒有動機，而且偽造的結果是保守的）；讓自己變好看的宣告直接拒絕，`COMPLETE = True` 會讓建置失敗。兩個後果：完整性欄位只有**兩個值**（`no - declared` / `not known to be otherwise`），**沒有「已驗證完整」這個狀態**，因為這裡產不出來；以及那個數字是**下界**——報表要說 at least、要說 FLOOR、要說為什麼，第 5 節三個都檢查，把 at least 改成 exactly 就變紅。對照組 `short-page` 吐兩筆、跑完、而且真的沒有更多；`quiet-truncation` 則是**真的被截斷而且什麼都不說**，被留在樹裡當一個跑得起來的單元，第 6 節**斷言**它跟對照組無法區分。同日考古 017 量到最利的版本：截斷的 zlib 串流跟完整串流解出來**位元組完全相同**，唯一分得開的是 `.eof`，而 `.eof` 在物件上、bytes 是回傳值。",
      "en": "Example 016 took `finished` away from the unit by having the collector observe it, and the same day I wrote down the cost on the board - a source that knows it did not return everything now has nowhere to say so. This entry pays that cost back. Four sources all finish and none fails, and they are not all complete. Completeness cannot be observed from outside the unit, so it has to be declared, and 016 had just concluded that a fact a unit could get wrong should not be the unit's to state. The resolution is directional - a unit may declare itself incomplete and may not declare itself complete. A declaration that can only make the report worse for the declarer is taken on trust; one that makes it better is refused, and COMPLETE = True fails the build. Two consequences: the completeness column has two values and there is no verified-complete state, because nothing here can produce one; and the number is a floor, so the report says \"at least\", says FLOOR, and says why, with a mutation from \"at least\" to \"exactly\" turning it red. The control is short-page, which returns two records, finishes, and genuinely has nothing more. quiet-truncation is truncated and silent and is kept in the tree as a running unit, with section 6 asserting that it is indistinguishable from the control. The same day's archaeology measures the sharpest version: a truncated zlib stream and a complete one decompress to byte-identical output and only .eof separates them, and .eof is on the object while the bytes are the return value."
    },
    "language": "python",
    "date": "2026-08-17",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "finished-and-complete-are-two-axes",
      "a-unit-may-declare-itself-incomplete-not-complete",
      "there-is-no-verified-complete-state",
      "the-number-is-a-floor-and-must-say-so",
      "the-gap-is-kept-in-the-tree-as-a-running-unit"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/__init__.py",
      "DMS/report.py",
      "FMS/__init__.py",
      "FMS/contract.json",
      "SCL/__init__.py",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/__init__.py",
      "SMS/gather.py",
      "TMS/__init__.py",
      "TMS/sources/__init__.py",
      "TMS/sources/full_page.py",
      "TMS/sources/quiet_truncation.py",
      "TMS/sources/short_page.py",
      "TMS/sources/truncated_page.py",
      "island_test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/__init__.py",
        "FMS/contract.json"
      ],
      "SCL": [
        "SCL/__init__.py",
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/__init__.py",
        "SMS/gather.py"
      ],
      "TMS": [
        "TMS/__init__.py",
        "TMS/sources/__init__.py",
        "TMS/sources/full_page.py",
        "TMS/sources/quiet_truncation.py",
        "TMS/sources/short_page.py",
        "TMS/sources/truncated_page.py"
      ],
      "DMS": [
        "DMS/__init__.py",
        "DMS/report.py"
      ],
      "root": [
        "island_test.py",
        "main.py"
      ]
    },
    "lineCount": 473,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/017-finished-is-not-complete.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/017-finished-is-not-complete.html"
  }
];

export const msspExampleCount = 17;
