// Generated by scripts/build-mssp-discussions.mjs. Do not edit by hand.
export type MsspDiscussion = {
  id: string; title: string; status: string; opened: string; updated: string;
  openedBy: string; managedBy: string; summary: string; relates: string[]; tags: string[];
  decisionRef: string; href: string; canonicalUrl: string; sourceUrl: string;
};

export const msspDiscussions: MsspDiscussion[] = [];

export const msspDiscussionCount = 0;
export const msspDiscussionOpenCount = 0;
export const msspDiscussionGuide = {"href":"/html/mssp/discussions/guide.html","canonicalUrl":"https://thisoneisneok.com/html/mssp/discussions/guide.html"};
