// Generated by scripts/build-mssp.mjs. Do not edit by hand.
export const msspExamples = [
  {
    "id": "001-task-runner",
    "slug": "001-task-runner",
    "title": {
      "zh": "任務執行器：兩個 TMS 想互相引用時",
      "en": "Task Runner: when two TMS want to import each other"
    },
    "summary": {
      "zh": "兩個報表模組需要同一份計算結果。直接互相引用會讓其中一個永遠無法單獨載入；改由 SMS 持有共享契約後，兩者都通過孤島測試。",
      "en": "Two reporters need the same computed result. Importing one from the other leaves one of them permanently unloadable alone; moving the shared contract into SMS lets both pass the island test."
    },
    "language": "javascript",
    "date": "2026-07-31",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "tms-to-tms-coupling",
      "sms-shared-contract",
      "island-test"
    ],
    "runnable": "node src/main.js",
    "files": [
      "DMS/trace.js",
      "FMS/manifest.json",
      "SCL/permissions.js",
      "SCL/permissions.json",
      "SMS/model.js",
      "SMS/registry.js",
      "SMS/runner.js",
      "TMS/handlers/file-read.js",
      "TMS/handlers/http-get.js",
      "TMS/reporters/json.js",
      "TMS/reporters/text.js",
      "island-test.js",
      "main.js"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/permissions.js",
        "SCL/permissions.json"
      ],
      "SMS": [
        "SMS/model.js",
        "SMS/registry.js",
        "SMS/runner.js"
      ],
      "TMS": [
        "TMS/handlers/file-read.js",
        "TMS/handlers/http-get.js",
        "TMS/reporters/json.js",
        "TMS/reporters/text.js"
      ],
      "DMS": [
        "DMS/trace.js"
      ],
      "root": [
        "island-test.js",
        "main.js"
      ]
    },
    "lineCount": 509,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/001-task-runner.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/001-task-runner.html"
  },
  {
    "id": "002-link-checker",
    "slug": "002-link-checker",
    "title": {
      "zh": "連結檢查器：把一個 TMS 升成 SMS，然後付出代價",
      "en": "Link checker: promoting a TMS to SMS, and paying for it"
    },
    "summary": {
      "zh": "節流原本是可選能力，但沒有它主迴圈根本跑不完——它是核心。升上去之後，一個完全不碰網路的檢查器開始為它付出等待，代價是可以量出來的。",
      "en": "Pacing was optional until the loop stopped closing without it, which makes it core. Promoting it made a checker that never touches the network start paying for it, and the cost is a number you can read."
    },
    "language": "python",
    "date": "2026-08-02",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "tms-to-sms-promotion",
      "identity-test",
      "everything-becomes-sms",
      "island-test"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/trace.py",
      "FMS/manifest.json",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/model.py",
      "SMS/pacing.py",
      "SMS/pipeline.py",
      "TMS/checkers/anchor.py",
      "TMS/checkers/http.py",
      "TMS/reporters/text.py",
      "island-test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/model.py",
        "SMS/pacing.py",
        "SMS/pipeline.py"
      ],
      "TMS": [
        "TMS/checkers/anchor.py",
        "TMS/checkers/http.py",
        "TMS/reporters/text.py"
      ],
      "DMS": [
        "DMS/trace.py"
      ],
      "root": [
        "island-test.py",
        "main.py"
      ]
    },
    "lineCount": 730,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/002-link-checker.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/002-link-checker.html"
  }
];

export const msspExampleCount = 2;
