// Generated by scripts/build-archaeology.mjs. Do not edit by hand.
export const archaeology = [
  {
    "id": "002-http-server",
    "project": "CPython http.server",
    "license": "PSF-2.0",
    "examinedVersion": "3.14.5",
    "upstream": "https://github.com/python/cpython/blob/main/Lib/http/server.py",
    "title": {
      "zh": "http.server 3.14.5：當擴充點是繼承，子集就無法單獨存在",
      "en": "http.server 3.14.5: when the extension point is inheritance, no subset can stand alone"
    },
    "summary": {
      "zh": "1,441 行，BaseHTTPRequestHandler 28 個方法。新增一個動詞的方式是繼承整個類別再命名一個 do_X，於是每個「子集」都是「全部 ＋ 一個方法」。handle_one_request 一個方法同時讀 socket、解析、用 getattr 分派、寫回應、記錄；log_message 寫死 sys.stderr。重切後 do_GET 的對應物不需要 socket 就能單獨測。",
      "en": "1,441 lines, 28 methods on BaseHTTPRequestHandler. Adding a verb means subclassing the whole thing and naming a method do_X, so every \"subset\" is the whole plus one method. handle_one_request reads the socket, parses, dispatches by getattr, writes the response and logs, all in one method; log_message is hardcoded to sys.stderr. After the re-cut, the equivalent of do_GET runs alone with no socket."
    },
    "date": "2026-08-02",
    "verdict": "seam-confirmed-by-ecosystem",
    "concepts": [
      "inheritance-blocks-the-island-test",
      "registry-vs-naming-convention",
      "dms-is-a-sink-not-a-destination"
    ],
    "lineCount": 514,
    "href": "/html/mssp/archaeology/002-http-server.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/archaeology/002-http-server.html"
  },
  {
    "id": "001-commander",
    "project": "commander",
    "license": "MIT",
    "examinedVersion": "2.20.3",
    "upstream": "https://github.com/tj/commander.js",
    "title": {
      "zh": "commander 2.20.3：解析結果與宿主效果之間的那條縫",
      "en": "commander 2.20.3: the seam between a parse result and a host effect"
    },
    "summary": {
      "zh": "1,225 行、一個檔案、36 個原型方法，其中 8 處直接呼叫 process.exit()。解析錯誤是知識，終止行程是效果，2.x 把兩者焊在一起。上游後來在 v4 和 v7 分別畫出了同樣的兩條界線。",
      "en": "1,225 lines in one file, 36 prototype methods, 8 direct calls to process.exit(). A parse error is knowledge; terminating the host is an effect. 2.x fuses them. Upstream drew the same two boundaries itself, at v4 and v7."
    },
    "date": "2026-08-01",
    "verdict": "seam-confirmed-upstream",
    "concepts": [
      "knowledge-vs-permission",
      "decision-vs-effect",
      "scl-owns-the-effect"
    ],
    "lineCount": 401,
    "href": "/html/mssp/archaeology/001-commander.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/archaeology/001-commander.html"
  }
];

export const archaeologyCount = 2;
