// Generated by scripts/build-archaeology.mjs. Do not edit by hand.
export const archaeology = [
  {
    "id": "001-commander",
    "project": "commander",
    "license": "MIT",
    "examinedVersion": "2.20.3",
    "upstream": "https://github.com/tj/commander.js",
    "title": {
      "zh": "commander 2.20.3：解析結果與宿主效果之間的那條縫",
      "en": "commander 2.20.3: the seam between a parse result and a host effect"
    },
    "summary": {
      "zh": "1,225 行、一個檔案、36 個原型方法，其中 8 處直接呼叫 process.exit()。解析錯誤是知識，終止行程是效果，2.x 把兩者焊在一起。上游後來在 v4 和 v7 分別畫出了同樣的兩條界線。",
      "en": "1,225 lines in one file, 36 prototype methods, 8 direct calls to process.exit(). A parse error is knowledge; terminating the host is an effect. 2.x fuses them. Upstream drew the same two boundaries itself, at v4 and v7."
    },
    "date": "2026-08-01",
    "verdict": "seam-confirmed-upstream",
    "concepts": [
      "knowledge-vs-permission",
      "decision-vs-effect",
      "scl-owns-the-effect"
    ],
    "lineCount": 401,
    "href": "/html/mssp/archaeology/001-commander.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/archaeology/001-commander.html"
  }
];

export const archaeologyCount = 1;
