// Generated by scripts/build-mssp.mjs from mssp/modules/*.md. Do not edit by hand.
export const msspModules = [
  {
    "id": "start",
    "index": "01",
    "title": {
      "zh": "從這裡開始",
      "en": "Start here"
    },
    "summary": {
      "zh": "MSSP 的問題意識、五個集合、兩個判斷問題，以及怎麼決定你的專案該用多少。",
      "en": "The motivation, the five sets, the two questions that decide placement, and how to choose how much of it your project should use."
    },
    "state": {
      "zh": "可讀",
      "en": "Readable"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/start.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/start.html"
  },
  {
    "id": "patterns",
    "index": "02",
    "title": {
      "zh": "架構與模式",
      "en": "Architecture & patterns"
    },
    "summary": {
      "zh": "五個已驗證的可重複結構、六種反模式，以及實作補上的一條規則。",
      "en": "Five verified reusable structures, six anti-patterns, and one rule implementation added to the method."
    },
    "state": {
      "zh": "演化中",
      "en": "Evolving"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/patterns.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/patterns.html"
  },
  {
    "id": "archaeology",
    "index": "03",
    "title": {
      "zh": "開源專案考古",
      "en": "Open-source archaeology"
    },
    "summary": {
      "zh": "每天拆解一個開源專案的結構，優先挑寬鬆授權的。看它的邊界畫在哪裡、為什麼畫在那裡。",
      "en": "One open-source project a day, permissive licences first — where its boundaries sit, and why they sit there."
    },
    "state": {
      "zh": "每日進行",
      "en": "Daily"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/archaeology.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/archaeology.html"
  },
  {
    "id": "reference",
    "index": "04",
    "title": {
      "zh": "參考實作",
      "en": "Reference implementations"
    },
    "summary": {
      "zh": "可執行的範例。每個只示範一個結構決策，並在建置時被機械檢查。目前 1 個。",
      "en": "Runnable examples, each demonstrating one structural decision and checked mechanically at build time. One so far."
    },
    "state": {
      "zh": "進行中",
      "en": "In progress"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/reference.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/reference.html"
  }
];
