// Generated by scripts/build-mssp.mjs. Do not edit by hand.
export const msspExamples = [
  {
    "id": "001-task-runner",
    "slug": "001-task-runner",
    "title": {
      "zh": "任務執行器：兩個 TMS 想互相引用時",
      "en": "Task Runner: when two TMS want to import each other"
    },
    "summary": {
      "zh": "兩個報表模組需要同一份計算結果。直接互相引用會讓其中一個永遠無法單獨載入；改由 SMS 持有共享契約後，兩者都通過孤島測試。",
      "en": "Two reporters need the same computed result. Importing one from the other leaves one of them permanently unloadable alone; moving the shared contract into SMS lets both pass the island test."
    },
    "language": "javascript",
    "date": "2026-07-31",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "tms-to-tms-coupling",
      "sms-shared-contract",
      "island-test"
    ],
    "runnable": "node src/main.js",
    "files": [
      "DMS/trace.js",
      "FMS/manifest.json",
      "SCL/permissions.js",
      "SCL/permissions.json",
      "SMS/model.js",
      "SMS/registry.js",
      "SMS/runner.js",
      "TMS/handlers/file-read.js",
      "TMS/handlers/http-get.js",
      "TMS/reporters/json.js",
      "TMS/reporters/text.js",
      "island-test.js",
      "main.js"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/permissions.js",
        "SCL/permissions.json"
      ],
      "SMS": [
        "SMS/model.js",
        "SMS/registry.js",
        "SMS/runner.js"
      ],
      "TMS": [
        "TMS/handlers/file-read.js",
        "TMS/handlers/http-get.js",
        "TMS/reporters/json.js",
        "TMS/reporters/text.js"
      ],
      "DMS": [
        "DMS/trace.js"
      ],
      "root": [
        "island-test.js",
        "main.js"
      ]
    },
    "lineCount": 509,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/001-task-runner.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/001-task-runner.html"
  },
  {
    "id": "002-link-checker",
    "slug": "002-link-checker",
    "title": {
      "zh": "連結檢查器：把一個 TMS 升成 SMS，然後付出代價",
      "en": "Link checker: promoting a TMS to SMS, and paying for it"
    },
    "summary": {
      "zh": "節流原本是可選能力，但沒有它主迴圈根本跑不完——它是核心。升上去之後，一個完全不碰網路的檢查器開始為它付出等待，代價是可以量出來的。",
      "en": "Pacing was optional until the loop stopped closing without it, which makes it core. Promoting it made a checker that never touches the network start paying for it, and the cost is a number you can read."
    },
    "language": "python",
    "date": "2026-08-02",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "tms-to-sms-promotion",
      "identity-test",
      "everything-becomes-sms",
      "island-test"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/trace.py",
      "FMS/manifest.json",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/model.py",
      "SMS/pacing.py",
      "SMS/pipeline.py",
      "TMS/checkers/anchor.py",
      "TMS/checkers/http.py",
      "TMS/reporters/text.py",
      "island-test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/model.py",
        "SMS/pacing.py",
        "SMS/pipeline.py"
      ],
      "TMS": [
        "TMS/checkers/anchor.py",
        "TMS/checkers/http.py",
        "TMS/reporters/text.py"
      ],
      "DMS": [
        "DMS/trace.py"
      ],
      "root": [
        "island-test.py",
        "main.py"
      ]
    },
    "lineCount": 730,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/002-link-checker.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/002-link-checker.html"
  },
  {
    "id": "003-record-migration",
    "slug": "003-record-migration",
    "title": {
      "zh": "記錄遷移：「500 筆，0 錯誤」是什麼意思",
      "en": "Record migration: what \\\"500 migrated, 0 errors\\\" actually says"
    },
    "summary": {
      "zh": "一次成功的執行報告，跟一次什麼都沒做的執行報告，可以長得一模一樣。DMS 的工作不是記錄發生過什麼，是讓「成功」變成可以查證的——收支要平、每個轉換要交出見證、沒被呼叫過的要自己說出來。",
      "en": "A successful run and a run that did nothing can print the same report. The job of DMS is not to log what happened but to make success checkable — the arithmetic has to balance, every transform has to produce a witness, and one that was never invoked has to say so itself."
    },
    "language": "javascript",
    "date": "2026-08-03",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "dms-makes-success-checkable",
      "reconciliation",
      "unexercised-capability",
      "island-test"
    ],
    "runnable": "node src/main.js",
    "files": [
      "DMS/ledger.js",
      "FMS/manifest.json",
      "SCL/policy.js",
      "SCL/policy.json",
      "SMS/model.js",
      "SMS/pipeline.js",
      "SMS/reconcile.js",
      "TMS/transforms/normalise-phone.js",
      "TMS/transforms/split-name.js",
      "island-test.js",
      "main.js"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/policy.js",
        "SCL/policy.json"
      ],
      "SMS": [
        "SMS/model.js",
        "SMS/pipeline.js",
        "SMS/reconcile.js"
      ],
      "TMS": [
        "TMS/transforms/normalise-phone.js",
        "TMS/transforms/split-name.js"
      ],
      "DMS": [
        "DMS/ledger.js"
      ],
      "root": [
        "island-test.js",
        "main.js"
      ]
    },
    "lineCount": 631,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/003-record-migration.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/003-record-migration.html"
  },
  {
    "id": "004-router",
    "slug": "004-router",
    "title": {
      "zh": "Router：回傳名字，不回傳模組",
      "en": "Router: it returns a name, not a module"
    },
    "summary": {
      "zh": "一個會 import 它所選之物的路由器，測試它就得載入全部候選——於是路由本身沒有孤島測試可跑。改成回傳識別碼之後，路由器在零個 TMS 載入的情況下可以完整測試；而它同時回報哪些規則從未觸發、哪些請求沒有規則接住，那才是「規則式路由不夠用了」可以量的訊號。",
      "en": "A router that imports what it selects can only be tested with every candidate loaded, so routing itself has no island test. Returning an identifier instead lets the router be exercised with zero TMS present — and having it report which rules never fired and which requests nothing matched turns \"rule-based routing has stopped being enough\" into something measurable rather than felt."
    },
    "language": "python",
    "date": "2026-08-04",
    "version": "v1.0",
    "kind": "example",
    "concepts": [
      "router-returns-an-identifier",
      "island-test-for-the-router-itself",
      "routing-coverage-as-a-scale-signal"
    ],
    "runnable": "python src/main.py",
    "files": [
      "DMS/ledger.py",
      "FMS/manifest.json",
      "SCL/policy.json",
      "SCL/policy.py",
      "SMS/model.py",
      "SMS/router.py",
      "TMS/handlers/csv.py",
      "TMS/handlers/markdown.py",
      "island-test.py",
      "main.py"
    ],
    "bySet": {
      "FMS": [
        "FMS/manifest.json"
      ],
      "SCL": [
        "SCL/policy.json",
        "SCL/policy.py"
      ],
      "SMS": [
        "SMS/model.py",
        "SMS/router.py"
      ],
      "TMS": [
        "TMS/handlers/csv.py",
        "TMS/handlers/markdown.py"
      ],
      "DMS": [
        "DMS/ledger.py"
      ],
      "root": [
        "island-test.py",
        "main.py"
      ]
    },
    "lineCount": 503,
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/004-router.html",
    "htmlUrl": "https://thisoneisneok.com/html/mssp/004-router.html"
  }
];

export const msspExampleCount = 4;
