// Generated by scripts/build-mssp.mjs from mssp/modules/*.md. Do not edit by hand.
export const msspModules = [
  {
    "id": "start",
    "index": "01",
    "title": {
      "zh": "從這裡開始",
      "en": "Start here"
    },
    "summary": {
      "zh": "用最少前置知識理解 MSSP 的問題意識、基本組件與適用邊界。",
      "en": "Understand the motivation, base components, and boundaries of MSSP with minimal prerequisites."
    },
    "state": {
      "zh": "可讀",
      "en": "Readable"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/start.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/start.html"
  },
  {
    "id": "patterns",
    "index": "02",
    "title": {
      "zh": "架構與模式",
      "en": "Architecture & patterns"
    },
    "summary": {
      "zh": "狀態拆分、共享契約、孤島測試與檢查順序等可重複使用的結構，以及六種反模式。",
      "en": "Reusable structures for state separation, shared contracts, island testing, and check ordering — plus six anti-patterns."
    },
    "state": {
      "zh": "演化中",
      "en": "Evolving"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/patterns.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/patterns.html"
  },
  {
    "id": "archaeology",
    "index": "03",
    "title": {
      "zh": "開源專案考古",
      "en": "Open-source archaeology"
    },
    "summary": {
      "zh": "分析既有專案的哪些結構可以保留、重寫或轉化為 MSSP。方法已定，目前完成 0 個。",
      "en": "Analysing what existing projects can preserve, rewrite, or transform into MSSP. The method is defined; zero projects have been done."
    },
    "state": {
      "zh": "尚未開始",
      "en": "Not started"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/archaeology.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/archaeology.html"
  },
  {
    "id": "reference",
    "index": "04",
    "title": {
      "zh": "參考實作",
      "en": "Reference implementations"
    },
    "summary": {
      "zh": "可執行的範例。每個只示範一個結構決策，並在建置時被機械檢查。目前 1 個。",
      "en": "Runnable examples, each demonstrating one structural decision and checked mechanically at build time. One so far."
    },
    "state": {
      "zh": "進行中",
      "en": "In progress"
    },
    "updated": "2026-07-31",
    "href": "/html/mssp/modules/reference.html",
    "canonicalUrl": "https://thisoneisneok.com/html/mssp/modules/reference.html"
  }
] as const;
