// Generated by scripts/build-research.mjs from research/manifest.json.
// Do not edit by hand — edit the manifest or the converted source.
export const researchPapers = [
  {
    "slug": "folder-programming-language",
    "direction": {
      "zh": "資料夾語言",
      "en": "Folder language"
    },
    "title": {
      "zh": "資料夾程式語言：從認知架構到可執行規範",
      "en": "Folder Programming Language: from cognitive architecture to executable specification"
    },
    "summary": {
      "zh": "把資料夾結構從「放檔案的容器」提升為語言本身的本體：目錄即宣告，路徑即語義，架構不再是描述程式的文件，而是可以被執行的規範。",
      "en": "Raises folder structure from a container that holds files into an entity of the language itself: a directory is a declaration and a path carries meaning, so architecture stops being a document about the program and becomes a specification that runs."
    },
    "status": {
      "zh": "研究草案",
      "en": "Research draft"
    },
    "date": "2026-08-01",
    "nameStatus": "provisional",
    "nameNote": {
      "zh": "正式名稱尚未定案，FPL 是目前的工作名。",
      "en": "The formal name is not settled; FPL is the working title."
    },
    "relatesTo": null,
    "charCount": 51080,
    "sectionCount": 11,
    "href": "/html/research/folder-programming-language.html",
    "canonicalUrl": "https://thisoneisneok.com/html/research/folder-programming-language.html",
    "mdUrl": "https://thisoneisneok.com/md/research/folder-programming-language.md"
  },
  {
    "slug": "github-architecture-scope",
    "direction": {
      "zh": "架構可視化",
      "en": "Architecture visualisation"
    },
    "title": {
      "zh": "GitHub 架構透視器：讓隱藏的架構可視化",
      "en": "GitHub Architecture Scope: making hidden architecture visible"
    },
    "summary": {
      "zh": "一個倉庫的真實架構藏在 import 圖、目錄慣例與變更歷史裡，讀 README 看不到。這篇提出把它直接畫出來，並且畫成人與 AI 都能消費的形式。",
      "en": "A repository's real architecture hides in its import graph, directory conventions, and change history — none of which a README shows. This proposes drawing it directly, in a form both a person and an agent can consume."
    },
    "status": {
      "zh": "研究草案",
      "en": "Research draft"
    },
    "date": "2026-08-01",
    "nameStatus": "settled",
    "nameNote": null,
    "relatesTo": null,
    "charCount": 17564,
    "sectionCount": 3,
    "href": "/html/research/github-architecture-scope.html",
    "canonicalUrl": "https://thisoneisneok.com/html/research/github-architecture-scope.html",
    "mdUrl": "https://thisoneisneok.com/md/research/github-architecture-scope.md"
  },
  {
    "slug": "scale-aware-architecture",
    "direction": {
      "zh": "動態 MSSP",
      "en": "Dynamic MSSP"
    },
    "title": {
      "zh": "軟體專案的規模感知架構組織範式",
      "en": "Scale-Aware Architecture Organisation for Software Projects"
    },
    "summary": {
      "zh": "從認知負荷、圖論與組織理論推導出「多大的專案該用多少結構」，並讓這個判斷隨專案成長自動演化，而不是在第一天就凍結一套模板。",
      "en": "Derives how much structure a project of a given size should carry, from cognitive load, graph theory, and organisational theory — and lets that judgement evolve as the project grows instead of freezing a template on day one."
    },
    "status": {
      "zh": "研究草案",
      "en": "Research draft"
    },
    "date": "2026-08-01",
    "nameStatus": "settled",
    "nameNote": null,
    "relatesTo": {
      "zh": "直接對應 MSSP 手冊裡的「度」，並把它從一張表格推進成可推導的模型。",
      "en": "Directly extends the field manual's notion of the right amount, pushing it from a table into a derivable model."
    },
    "charCount": 20976,
    "sectionCount": 6,
    "href": "/html/research/scale-aware-architecture.html",
    "canonicalUrl": "https://thisoneisneok.com/html/research/scale-aware-architecture.html",
    "mdUrl": "https://thisoneisneok.com/md/research/scale-aware-architecture.md"
  },
  {
    "slug": "ai-static-memory-bounds",
    "direction": {
      "zh": "AI 管理",
      "en": "AI management"
    },
    "title": {
      "zh": "AI 驅動的靜態記憶體邊界推斷系統",
      "en": "AI-Driven Static Memory Bound Inference"
    },
    "summary": {
      "zh": "在 MSSP 的模組邊界之上做後驗式靜態推斷：讓 AI 推出每個模組的記憶體上界，取代動態管理的不可預測與傳統靜態分析的過度保守。",
      "en": "Posterior static inference on top of MSSP's module boundaries: an AI derives a memory upper bound per module, replacing both the unpredictability of dynamic management and the over-conservatism of classical static analysis."
    },
    "status": {
      "zh": "研究草案",
      "en": "Research draft"
    },
    "date": "2026-08-01",
    "nameStatus": "settled",
    "nameNote": null,
    "relatesTo": {
      "zh": "唯一一篇直接建立在 MSSP 架構之上的研究——模組邊界是它的推斷單位。",
      "en": "The only one of the four built directly on MSSP: its module boundaries are the unit the inference works over."
    },
    "charCount": 109239,
    "sectionCount": 19,
    "href": "/html/research/ai-static-memory-bounds.html",
    "canonicalUrl": "https://thisoneisneok.com/html/research/ai-static-memory-bounds.html",
    "mdUrl": "https://thisoneisneok.com/md/research/ai-static-memory-bounds.md"
  }
];

export const researchCount = 4;
export const researchDirectionNote = {
  "zh": "這四篇對應 MSSP 接下來的四個方向：AI 管理、資料夾語言、架構可視化（人與 AI 都看得懂），以及動態／規模感知的 MSSP。它們不是 MSSP 現況的說明，是它下一批版本的材料。",
  "en": "These four map onto the four directions MSSP is heading: AI management, a folder language, architecture visualisation legible to people and to AI alike, and a dynamic, scale-aware MSSP. They describe where the method is going, not where it currently is."
};
