// Generated by scripts/build-research.mjs from research/manifest.json.
// Do not edit by hand — edit the manifest or the converted source.
export const researchPapers = [
  {
    "slug": "evemiss-fpl",
    "direction": {
      "zh": "FPL 專案形式化語言",
      "en": "Formal Project Language"
    },
    "title": {
      "zh": "EveMiss FPL 專案形式化語言",
      "en": "EveMiss FPL — Formal Project Language"
    },
    "summary": {
      "zh": "把專案架構本身變成一種可執行的語言：MSSP-Lang 定義模組與關係，編譯器把它展開成專案骨架，AI 負責中觀架構生成與微觀實作，人類保留宏觀決策。操作的對象不是資料與邏輯，是模組與關係。",
      "en": "Turns project architecture itself into an executable language: MSSP-Lang declares modules and relations, a compiler expands that into the project skeleton, and an AI fills in structure and code while the human keeps the macro decisions. What you manipulate is not data and logic but modules and relations."
    },
    "status": {
      "zh": "研究草案",
      "en": "Research draft"
    },
    "date": "2026-08-01",
    "subtitle": {
      "zh": "面向 AI 原生軟體開發的可執行架構語言",
      "en": "An Executable Architecture Language for AI-Native Software Development"
    },
    "nameStatus": "settled",
    "nameNote": null,
    "formerName": {
      "zh": "撰寫時的工作名稱為「資料夾程式語言（Folder Programming Language）」。縮寫 FPL 沿用，展開由 Folder 改為 Formal。",
      "en": "Written under the working title Folder Programming Language. The initialism is kept; the expansion changed from Folder to Formal."
    },
    "relatesTo": {
      "zh": "直接建在 MSSP 之上：MSSP-Lang 的語法單位就是 FMS／SCL／SMS／TMS／DMS，而母集與子集的判準是它的型別規則。",
      "en": "Built directly on MSSP: MSSP-Lang's syntactic units are the five sets, and the mother-set/subset criteria are its typing rules."
    },
    "charCount": 51388,
    "sectionCount": 11,
    "href": "/html/research/evemiss-fpl.html",
    "canonicalUrl": "https://thisoneisneok.com/html/research/evemiss-fpl.html",
    "mdUrl": "https://thisoneisneok.com/md/research/evemiss-fpl.md"
  },
  {
    "slug": "github-architecture-scope",
    "direction": {
      "zh": "架構可視化",
      "en": "Architecture visualisation"
    },
    "title": {
      "zh": "GitHub 架構透視器：讓隱藏的架構可視化",
      "en": "GitHub Architecture Scope: making hidden architecture visible"
    },
    "summary": {
      "zh": "一個倉庫的真實架構藏在 import 圖、目錄慣例與變更歷史裡，讀 README 看不到。這篇提出把它直接畫出來，並且畫成人與 AI 都能消費的形式。",
      "en": "A repository's real architecture hides in its import graph, directory conventions, and change history — none of which a README shows. This proposes drawing it directly, in a form both a person and an agent can consume."
    },
    "status": {
      "zh": "研究草案",
      "en": "Research draft"
    },
    "date": "2026-08-01",
    "subtitle": null,
    "nameStatus": "settled",
    "nameNote": null,
    "formerName": null,
    "relatesTo": null,
    "charCount": 17564,
    "sectionCount": 3,
    "href": "/html/research/github-architecture-scope.html",
    "canonicalUrl": "https://thisoneisneok.com/html/research/github-architecture-scope.html",
    "mdUrl": "https://thisoneisneok.com/md/research/github-architecture-scope.md"
  },
  {
    "slug": "scale-aware-architecture",
    "direction": {
      "zh": "動態 MSSP",
      "en": "Dynamic MSSP"
    },
    "title": {
      "zh": "軟體專案的規模感知架構組織範式",
      "en": "Scale-Aware Architecture Organisation for Software Projects"
    },
    "summary": {
      "zh": "從認知負荷、圖論與組織理論推導出「多大的專案該用多少結構」，並讓這個判斷隨專案成長自動演化，而不是在第一天就凍結一套模板。",
      "en": "Derives how much structure a project of a given size should carry, from cognitive load, graph theory, and organisational theory — and lets that judgement evolve as the project grows instead of freezing a template on day one."
    },
    "status": {
      "zh": "研究草案",
      "en": "Research draft"
    },
    "date": "2026-08-01",
    "subtitle": null,
    "nameStatus": "settled",
    "nameNote": null,
    "formerName": null,
    "relatesTo": {
      "zh": "直接對應 MSSP 手冊裡的「度」，並把它從一張表格推進成可推導的模型。",
      "en": "Directly extends the field manual's notion of the right amount, pushing it from a table into a derivable model."
    },
    "charCount": 20976,
    "sectionCount": 6,
    "href": "/html/research/scale-aware-architecture.html",
    "canonicalUrl": "https://thisoneisneok.com/html/research/scale-aware-architecture.html",
    "mdUrl": "https://thisoneisneok.com/md/research/scale-aware-architecture.md"
  },
  {
    "slug": "ai-static-memory-bounds",
    "direction": {
      "zh": "AI 管理",
      "en": "AI management"
    },
    "title": {
      "zh": "AI 驅動的靜態記憶體邊界推斷系統",
      "en": "AI-Driven Static Memory Bound Inference"
    },
    "summary": {
      "zh": "在 MSSP 的模組邊界之上做後驗式靜態推斷：讓 AI 推出每個模組的記憶體上界，取代動態管理的不可預測與傳統靜態分析的過度保守。",
      "en": "Posterior static inference on top of MSSP's module boundaries: an AI derives a memory upper bound per module, replacing both the unpredictability of dynamic management and the over-conservatism of classical static analysis."
    },
    "status": {
      "zh": "研究草案",
      "en": "Research draft"
    },
    "date": "2026-08-01",
    "subtitle": null,
    "nameStatus": "settled",
    "nameNote": null,
    "formerName": null,
    "relatesTo": {
      "zh": "推斷的單位就是 MSSP 的模組邊界——沒有那條邊界，靜態上界只能退回整個程式的保守估計。",
      "en": "The unit it infers over is an MSSP module boundary. Without that boundary a static upper bound falls back to a conservative estimate over the whole program."
    },
    "charCount": 109239,
    "sectionCount": 19,
    "href": "/html/research/ai-static-memory-bounds.html",
    "canonicalUrl": "https://thisoneisneok.com/html/research/ai-static-memory-bounds.html",
    "mdUrl": "https://thisoneisneok.com/md/research/ai-static-memory-bounds.md"
  }
];

export const researchCount = 4;
export const researchDirectionNote = {
  "zh": "這四篇對應 MSSP 接下來的四個方向：AI 管理、EveMiss FPL 專案形式化語言、架構可視化（人與 AI 都看得懂），以及動態／規模感知的 MSSP。它們不是 MSSP 現況的說明，是它下一批版本的材料。",
  "en": "These four map onto the four directions MSSP is heading: AI management, EveMiss FPL, architecture visualisation legible to people and to AI alike, and a dynamic, scale-aware MSSP. They describe where the method is going, not where it currently is."
};
