// Stamps one build_id into both the app and the machine layer, BEFORE the site
// is built, so every published surface can be checked against it afterwards.
//
// Why an id and not just counts: two different builds can coincidentally have
// the same paper count, but can never coincidentally share a build_id. That is
// what makes scripts/verify-deploy.mjs able to prove a deploy actually landed
// rather than reading a stale edge cache that happens to have the right totals.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

const root = process.cwd();
const generatedAt = new Date().toISOString();
const buildId = `${generatedAt.slice(0, 10).replace(/-/g, "")}-${crypto.randomBytes(4).toString("hex")}`;

function countPapers() {
  const file = path.join(root, "app", "data", "papers.generated.ts");
  if (!fs.existsSync(file)) return 0;
  const source = fs.readFileSync(file, "utf8");
  const match = source.match(/export const paperCount = (\d+)/);
  return match ? Number(match[1]) : 0;
}

function countPosts() {
  const dir = path.join(root, "content", "blog");
  if (!fs.existsSync(dir)) return 0;
  const slugs = new Set(
    fs.readdirSync(dir).filter((n) => n.endsWith(".md")).map((n) => n.replace(/\.(zh|en)\.md$/, "")),
  );
  return slugs.size;
}

const truth = {
  build_id: buildId,
  generated_at: generatedAt,
  paper_count: countPapers(),
  post_count: countPosts(),
};

fs.mkdirSync(path.join(root, "app", "data"), { recursive: true });
fs.writeFileSync(
  path.join(root, "app", "data", "build-id.generated.ts"),
  `// Generated by scripts/stamp-build.mjs. Do not edit by hand.\n` +
    `export const BUILD_ID = ${JSON.stringify(buildId)};\n` +
    `export const BUILD_GENERATED_AT = ${JSON.stringify(generatedAt)};\n`,
);

fs.mkdirSync(path.join(root, "public", "ai"), { recursive: true });
fs.writeFileSync(path.join(root, "public", "ai", "build-id.json"), `${JSON.stringify(truth, null, 2)}\n`);

console.log(`Stamped build_id=${buildId} papers=${truth.paper_count} posts=${truth.post_count}`);
